### ISSUE TITLE
Unable to open modal from dropdown

### ISSUE THREAD

**Issue by shilpaprabhun** [valor-software/ngx-bootstrap#1491] opened 2017-01-13 04:43 UTC
I have three components - app, sideNav and wallForm. In the app header, I have a button that drops down the sideNav. The sideNav has an add button which opens the wallForm modal. This is an ng2-bootstrap modal. The drop down menu loads fine, but when I click on the add button, the modal loads and the screen greys out (disabled), but the modal does not show in the front. I know it has loaded because I can inspect the element in browser developer tools. I tried setting the z-index of the modal to a very high number, much higher than that of the drop down menu and that didn't help. How do I get the modal to behave as it should i.e., display on top?

**Comment by valorkin** [comment] 2017-01-13 11:29
try to check this one https://github.com/valor-software/ng2-bootstrap/issues/1462#issuecomment-272226598

closing as duplicate

**Comment by shilpaprabhun** [comment] 2017-01-13 13:44
My issue remains unsolved. The navbar had position set to relative and I changed that to fixed. Now, when I click add button, nothing happens. It doesn't even grey out the background. Can this issue please be reopened?

**Comment by valorkin** [comment] 2017-01-13 18:04
Can you create a sample to reproduce?

**Comment by ToKaDev** [comment] 2017-01-18 11:14
Same problem here, can't open a modal dialog from my dropdown menu.
I only see the backdrop but no dialog.

**Comment by melwet** [comment] 2017-02-08 21:08
I'm also facing the same problem. The modal isn't opening when clicked from a dropdown menu. Is there any workaround for this problem?

**Comment by jdev27** [comment] 2017-02-27 14:02
Hi, i'm unable to open (correctly) the modal by clicking a button inside a carousel as well using template reference binding.
if there's a service to separate the trigger and the modal div into different component that would be helpful cause the bug is that when putting the modal div inside the carousel, the modal wouldn't open correctly, there's few example on other thread but the code is outdated and not really applicable anymore using the latest angular 2 codes. please advise thanks!

**Comment by valorkin** [comment] 2017-03-02 12:18
@shilpaprabhun ok, I have found what the problem is:
inheritance of z-index, but it could be solved only inside of your markup
what I can do: I am implementing modal service
it should simplify modals usage

**Closed as completed by valorkin** 2017-03-02 12:18 UTC
Labels: comp(modal)
