### ISSUE TITLE
problem with  BsModalService

### ISSUE THREAD

**Issue by nellyigiebor** [valor-software/ngx-bootstrap#2576] opened 2017-09-03 15:11 UTC
hi,

I'm having the same problem.
What's the solutions to this please ??

I'm trying to use BsModalService to show component as a modal but having this problem "Modal Backdrop is covering modal content".

Thanks in advance

**Comment by IlyaSurmay** [comment] 2017-09-04 13:19
Closing as a duplicate of #2527 
There's no need to create a new issue if there's another opened issue on your subject

**Closed as completed by IlyaSurmay** 2017-09-04 13:19 UTC
Labels: comp(modal)
