### ISSUE TITLE
feat(typeahead): add possibility of canceling ongoing requests when a new request is sent

### ISSUE THREAD

**Issue by micke911** [valor-software/ngx-bootstrap#1626] opened 2017-02-09 16:02 UTC
Hi!
I am using the typeahead component with an async data source in an environment were the internet is unstable. This can result in responses being returned out of order. The data displayed in the dropdown then gets overwritten with data from an older request.
What I need is the possibility to use something like switchMap to cancel ongoing requests when a new request is sent. I have tried replacing mergeMap with switchMap in the following code from the documentation but that did not change the behaviour.
```
public constructor() 
    {this.dataSource = Observable
      .create((observer: any) => {
        // Runs on every search
        observer.next(this.asyncSelected);
      })
      .mergeMap((token: string) => this.getStatesAsObservable(token));
  }
```

**Comment by micke911** [comment] 2017-02-14 07:59
I tried editing the asyncActions method in the typeahead.directive and changing mergeMap to switchMap and it seems to fix my issue.

      protected asyncActions(): void {
      this.keyUpEventEmitter
      .debounceTime(this.typeaheadWaitMs)
      .switchMap(() => this.typeahead)
      .subscribe(
        (matches: any[]) => {
          this.finalizeAsyncCall(matches);
        },
        (err: any) => {
          console.error(err);
        }
      );
  }

**Comment by ievgeniiVlasyuk** [comment] 2017-02-23 11:39
Hi!
Just faced with the same case.
Are there any plans for changing current behavior or maybe there are any other approach of canceling old API calls issued by typeahead component?

**Comment by SiasMey** [comment] 2017-02-27 22:39
I believe the described solution is exactly the intended behaviour.

The typeahead component doesnt actually do any filtering at all when you assign it a Observable as a data source. It expects you to provide filtering based on what is input so that the results provided by the observable are what you need them to be.

And for that, switchMap is exactly the right and intended solution. I did have some trouble making this work with a reactive form, but that was mostly because I didnt understand how easy observables actually made it.

You can also inject things like .distinct() and .debounceTime(400) to restrict how many requests are sent if you have an unreliable network connection.

**Comment by micke911** [comment] 2017-05-16 11:12
Hi!
Any progress on this issue? 
I'm happy to provide more information to clarify the issue if needed.

**Comment by fizdalf** [comment] 2018-02-15 10:33
MergeMap doesn't make sense, as it's effectively creating a new observable chain, and it will only unsubscribe when the directive is destroyed, and if you are making http requests, you soon are left with hundreds of the same http requests, and in turn finalizeAsyncCall is called hundreds of times..with the exact same data...

A catch could be there to prevent this one subscription from crashing in case an error bubbles up.

**Closed as completed** 2018-03-01 12:30 UTC
Labels: enhancement, effort1: easy (hours), comp(typeahead), prio: medium
