### ISSUE TITLE
bsdatepicker isopen is not working

### ISSUE THREAD

**Issue by cssuresh90** [valor-software/ngx-bootstrap#2717] opened 2017-09-24 15:31 UTC
hi 

bsdatepicker isopen is not working oniline 
<input class="form-control" placeholder="Datepicker" bsDatepicker [minDate]="minDate" [maxDate]="maxDate" #dp="bsDatepicker" [isOpen]="false">

**Comment by cssuresh90** [comment] 2017-09-24 15:32
hi all

bsdatepicker isopen is not working on inline
<input class="form-control" placeholder="Datepicker" bsDatepicker [minDate]="minDate" [maxDate]="maxDate" #dp="bsDatepicker" [isOpen]="false">

**Comment by IlyaSurmay** [comment] 2017-09-27 14:38
Duplicate of #2714

**Closed as completed by IlyaSurmay** 2017-09-27 14:38 UTC
