### ISSUE TITLE
DataPicker - change only month CallBack

### ISSUE THREAD

**Issue by michalmw** [valor-software/ngx-bootstrap#1711] opened 2017-03-05 09:41 UTC
Hello,

i need CallBack when user change month (just change navigating to another month).

E.x. on start i see July Month:
--> When user change month to another (next or prev) i need know that + what is now selected month.

Someone can help me?

**Comment by valorkin** [comment] 2017-08-22 11:55
I will keep it in mind...
for new datepicker (new style and pop up version)
available in v1.9.0+
check this out: http://valor-software.com/ngx-bootstrap/#/datepicker#examples

**Comment by valorkin** [comment] 2017-10-02 14:30
cleaning issues for roadmap
duplicate of #1153

**Closed as completed by valorkin** 2017-10-02 14:30 UTC
Labels: comp(datepicker)
