### ISSUE TITLE
gulp-typescript & gulp.src issue

### ISSUE THREAD

**Issue by SIGAN** [valor-software/ngx-bootstrap#186] opened 2016-02-13 23:19 UTC
Dear Valor team,

Could you please fix the following issue:
If you use `gulp-typescript` specifying source files using `gulp.src` and you specify to `outFile` to build a bundle, typescript will include ng2-bootstrap into that bundle. If you include `ng2-bootstrap.min.js` bundle on that page it won't work, if you don't - it won't work neither.

**The root cause:** 
Source `*.ts` files present in the same folder as `*.js` files in npm module.
And TypeScript just compiles it. `Exclude` option of `tsconfig.json` won't work, as it is ignoring it.

**How to fix:** 
It's very simple please make dedicated folder `src` and include `*.ts` files there. Other folders should contain only `*.js`, `*.js.map`, `*.d.ts` and no original `*.ts` files. 

Please take a look on Angular2 package for confirmation.

**Workaround:**
Currently we have to run gulp task to remove those files.

**PS:**
It will also fix issue #178

**Comment by valorkin** [comment] 2016-02-15 07:38
use TS 1.7.5 until ng2 supports 1.8
duplicate of #116

**Closed as completed by valorkin** 2016-02-15 07:38 UTC

**Comment by SIGAN** [comment] 2016-02-17 18:52
Please read carefully.

I have allowed unreachable code. It compiles and I don't see any compilation issues. And this actually doesn't matter.

The problem - is that it compiles `ng2-bootstrap` into my single file! 
And I don't want to compile it, I want to use `ng2-bootstrap.min.js` package, which is included.

But because TS compiler sees `*.ts` files in folder, it treats them as sources to compile, instead of just to use `*.d.ts` files.

I don't want to compile it in, because then I can't cache `ng2-bootstrap.min.js` package using browser. And clients will have to download my code & code of `ng2-bootstrap`!

And one more point - if I just remove `*.ts` files from `ng2-bootstrap` subfolder of `node_modules` it will work as expected.

Do you see the point?

**Comment by valorkin** [comment] 2016-02-17 19:03
Yeap, just add to ignore .ts files from node modules ng2 folders

**Comment by SIGAN** [comment] 2016-02-17 19:39
I have done it, but it ignores that parameter if you run with `gulp-typescript` :(

**Comment by valorkin** [comment] 2016-02-18 08:43
Can you add to ignore ts file from node modules in gulp files selector? (Blob)

**Comment by SIGAN** [comment] 2016-02-18 19:19
No, they are already ignored, because my selector includes only my files...
But tsc will expand that because I've imported them.

**Comment by valorkin** [comment] 2016-02-18 23:22
Not cool, not cool at all
On Monday I will be back to speed, so will get back to this issue
