### ISSUE TITLE
Feat(Calendar): I18n

### ISSUE THREAD

**Issue by ngonam22** [valor-software/ngx-bootstrap#1107] opened 2016-10-10 14:12 UTC
Should we have an option to change locale of moment js in ng2-calendar?

Right now, im doing this by modifying + adding new locale in date-formatter.ts, and it seems to be not a good way.

**Comment by adrianfaciu** [comment] 2016-10-10 17:17
Change it directly maybe: Moment.locale('en-us') ?

**Comment by ngonam22** [comment] 2016-10-11 04:02
I did do that. But based on which locale you choose, you have to require its specific locale moment js file.
And It also has some different configurations such as first day of the week, etc.

So should we change its locale via directive's input? (and the locale moment js file as well)

**Comment by valorkin** [comment] 2016-10-12 08:39
duplicate of #455 
- new version of datepicker is implemented
- and yes it supports i18n
- why not yet merged: I need to finish some infrastructure issues (build, docs and test in particular)

ng2 is released, and I have to focus on quality of code now

**Closed as completed by valorkin** 2016-10-12 08:39 UTC
