### ISSUE TITLE
fix(timepicker): keyboard/text changes to Timepicker "minutes" swaps AM/PM

### ISSUE THREAD

**Issue by todthomson** [valor-software/ngx-bootstrap#3132] opened 2017-11-29 00:04 UTC
When interacting with the `timepicker` component in 12-hour (AM/PM mode), keyboard/text-based changes to the `timepicker` "minutes" field followed by pressing the `tab` key swaps the AM/PM value when "hours" is set to `12`.

### Steps to reproduce

1. Go to https://valor-software.com/ngx-bootstrap/#/timepicker
1. Use the keyboard to set the "hours" field to `12` and press `tab`. You will notice that AM/PM swaps, which makes sense (at least to me) as you want AM/PM to switch when going from e.g. `9` to `12` as it would if you were updating it in increments via the up/down arrows.
1. Next use the keyboard to set the "minutes" field to any new value (e.g. change `50` to `49` or `51` and press `tab`, you will notice that the AM/PM again swaps, which doesn't make any sense (at least it doesn't to me) when updating the "minutes" value in this way.

### Thoughts

I can see that it makes some sense that when set to `11:59AM` and incrementing the `59` to `00` it would swap to `12:00PM` (which it does do, and that makes some logical sense), however i think `12:30AM` to `12:31PM` doesn't.

### Environment versions

ngx-bootstrap: `2.0.0-beta.9`
Angular: `4.4.6`
Bootstrap: `3.3.7`
Angular CLI: `1.4.9`

**Comment by rivanitskiy** [comment] 2018-08-07 12:54
I have the same issue. Do you have any forecasts when it will be fixed. 
**Environment versions**
Angular: `6.0.5`
ngx-bootsrap: `3.0.1`
bootstrap: `4.1.1`

**Comment by AayushG159** [comment] 2019-10-04 23:03
Would like to work on this issue

**Comment by daniloff200** [comment] 2020-01-30 15:22
looks like, that was fixed here : https://github.com/valor-software/ngx-bootstrap/pull/5535
At least, for now, with version 5.5.0 on  https://valor-software.com/ngx-bootstrap/#/timepicker I couldn't reproduce it

**Closed as completed by daniloff200** 2020-01-30 15:22 UTC
Labels: issue, comp(timepicker)

**Comment by pranavbhats** [comment] 2020-08-21 04:54
Version 5.5.0  is not compatible with angular 6.  Is there any solution?
