### ISSUE TITLE
feat(pagination): recalculate page numbers on page size change

### ISSUE THREAD

**Issue by mzaidipk** [valor-software/ngx-bootstrap#1339] opened 2016-12-14 18:46 UTC
It shows number of pages correct initially and paging is working but when i Change Page size like from 10 to 25 or above the number of pages remains same and it shows all pages rather than ... at the end list.

**Comment by valorkin** [comment] 2016-12-21 09:15
aha, got it. thing is pagination is not recalculated on page size change...
I will add to least of things to add

**Comment by IlyaSurmay** [comment] 2017-11-10 10:18
Closed as can't reproduce, will be reopened if we have sample to reproduce.
Tested on 2.0.0-beta.8 - https://plnkr.co/edit/pH5Qd2vX8zJQV8BCelTI?p=preview

**Closed as completed by IlyaSurmay** 2017-11-10 10:18 UTC
Labels: comp(pagination)
