### ISSUE TITLE
Typeahead showing previous query result

### ISSUE THREAD

**Issue by jindalrohit** [valor-software/ngx-bootstrap#2040] opened 2017-06-07 07:27 UTC
When i type **Jo** it's showing result for **J** when i type **Joh** it's showing result for **JO**, 
It's working behind one character. 
Please let me know how can i fix it.

**Comment by jindalrohit** [comment] 2017-06-07 14:23
There is issue with **typeahead-container.component.ts**.
**public get matches()** is not trigger properly after **public set matches ()** is called. When i manually called **ChangeDetectorRef.detectChanges()** in **public set matches()** then it worked fine. Please let me know is there any other way to fix this issue.

**Comment by harunurhan** [comment] 2017-09-20 11:31
@jindalrohit I reproduced it with `2.0.0-beta.1` but it was working fine for `1.9.3`. You can also give it try.

**Comment by IlyaSurmay** [comment] 2017-11-08 13:18
Is this still an issue in 2.0.0-beta.8 ? If so, please provide plunkr/stackblitz with reproduction
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IlyaSurmay** [comment] 2017-11-13 12:40
@harunurhan actually, `2.0.0-beta.1` is older than `1.9.3`
Closed as can't reproduce (with 2.0.0-beta.8) will be reopened if we have sample to reproduce

**Closed as completed by IlyaSurmay** 2017-11-13 12:40 UTC
Labels: comp(typeahead), needs: reproduce, can be closed?
