### ISSUE TITLE
Feature request: Integrate datepicker and timepicker

### ISSUE THREAD

**Issue by Pennywise83** [valor-software/ngx-bootstrap#2919] opened 2017-10-26 09:44 UTC
Hi,
I think that it would be a good thing to have timepicker integrated in date/daterange picker. In this way with only one input you could set a more precise daterange selecting also the hours.

**Comment by IlyaSurmay** [comment] 2017-10-26 11:57
Closing as a duplicate of #551

**Closed as completed by IlyaSurmay** 2017-10-26 11:57 UTC
