### ISSUE TITLE
How to localize Datepicker?

### ISSUE THREAD

**Issue by jfeenstra** [valor-software/ngx-bootstrap#2375] opened 2017-08-08 06:48 UTC
I'm unable to set the locale on Datepicker.
Our conclusion is the same as described in https://github.com/valor-software/ngx-bootstrap/issues/1882. Datepicker is using a different moment than the Moment that was configured globally.
Our global has locale 'nl', but Datepicker stays on 'en'. Even if we set the locale in App.component.ts. Could it be that we need to have the same version of `moment` in our global moment as used in ngxbootstrap?

But apart from that, is there an official description of how to configure localization for ngxbootstrap. I couldn't find it.

Thanks!

**Comment by IlyaSurmay** [comment] 2017-08-11 15:01
Duplicate of #455

**Closed as completed by IlyaSurmay** 2017-08-11 15:01 UTC
Labels: comp(datepicker)
