### ISSUE TITLE
Dropdown autoClose only when click outside the dropdown doesn't work. 

### ISSUE THREAD

**Issue by yassermuhammad** [valor-software/ngx-bootstrap#3886] opened 2018-02-27 10:46 UTC
### Bug description: 
I am trying to make dropdown close only when i click outside if i set [autoClose]="false" it's only close when i click on the element i open it from and if i set  [autoClose]="true" it closes if i click anywhere inside the dropdown.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.2

Angular: 4.4

Bootstrap: 4

**Comment by IlyaSurmay** [comment] 2018-03-01 12:27
Closed as a duplicate of #1933

**Closed as completed by IlyaSurmay** 2018-03-01 12:27 UTC
