### ISSUE TITLE
Does datepicker support month mode that means I only need year plus month not including days?

### ISSUE THREAD

**Issue by jamessawyer** [valor-software/ngx-bootstrap#2995] opened 2017-11-08 15:47 UTC
### Bug description or feature request:
feature(Datepicker): Does datepicker components support month mode or year mode that means I only need year plus month not including days or year only respectly?

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:v2.0.0-beta.8

Angular:

Bootstrap:

**Comment by jamessawyer** [comment] 2017-11-08 15:53
It may be the same issue in [#2627](https://github.com/valor-software/ngx-bootstrap/issues/2627)
I just found

**Comment by IlyaSurmay** [comment] 2017-11-09 10:24
Closing as a duplicate of  #2627

**Closed as completed by IlyaSurmay** 2017-11-09 10:24 UTC
Labels: comp(datepicker)
