### ISSUE TITLE
Error in ng2-bootstrap.umd.js

### ISSUE THREAD

**Issue by sdornan** [valor-software/ngx-bootstrap#1137] opened 2016-10-18 15:29 UTC
I upgraded ng2-bootstrap in my app to 1.1.14 and got an error when running a minified build of my app:

`Uncaught TypeError: Cannot set property 'name' of undefined` at `ng2-bootstrap.umd.js:1`

Any ideas?

**Comment by valorkin** [comment] 2016-10-19 11:23
duplicate of #1123 
please use common.js version with bundlers
umd for system.js for now

**Closed as completed** 2016-10-19 11:23 UTC
