### ISSUE TITLE
ng2-bootstrap tab select event fire multiple time

### ISSUE THREAD

**Issue by bschauhan** [valor-software/ngx-bootstrap#2005] opened 2017-05-29 14:08 UTC
i am use ng2-bootstrap **tabs** in our project. But, tab select event call multiple time. How to resolve it?

**HTML Code:**

```
<tabset [justified]="true" #staticTabs>
    <tab (select)="changeTab('teamtab',$event)" [active]="isCurrentTab == 'teamtab'">
        <!-- More Code -->
    </tab>
    <tab (select)="changeTab('formtab',$event)" [active]="isCurrentTab == 'formtab'">
        <!-- More Code -->
    </tab>
</tabset>
```

**Component code:**

```
changeTab(type, e){
    console.log(e);
}
```

**Comment by akmittal** [comment] 2017-07-03 18:23
It is duplicate of #1820 and #1129

**Comment by akmittal** [comment] 2017-07-03 18:24
Plunker to replicate issue

Workaround 

```
changeTab(type, e){
   if (!e.tabset) return;
    console.log(e);
}
```

**Closed as completed** 2017-08-04 20:26 UTC
Labels: comp(tabs)

**Comment by dave0688** [comment] 2018-03-05 13:06
I think I found an edge case here:

It still fires multiple requests for me in the following scenario: 
I have a form in each tab. When an input is focused, and I jump into the next input with tab (AND that input where I jumped in is NOT empty), then it fires the event three times.

The workaround works for me. Still would be nice if someone could fix that.

Thanks :)
