### ISSUE TITLE
Cannot find name 'Partial'

### ISSUE THREAD

**Issue by manjureddy7** [valor-software/ngx-bootstrap#2599] opened 2017-09-08 12:30 UTC
This issue exists.! Please help

i.node_modules/ngx-bootstrap/datepicker/bs-daterangepicker.component.d.ts (45,15): Cannot find name 'Partial'.

ii.node_modules/ngx-bootstrap/datepicker/bs-daterangepicker.component.d.ts (45,15): Cannot find name 'Partial'.

**Comment by IlyaSurmay** [comment] 2017-09-08 12:56
Closing as a duplicate of #2597

**Closed as completed by IlyaSurmay** 2017-09-08 12:56 UTC

**Comment by eva-Z** [comment] 2017-09-27 06:44
Have you solved the problem?
