### ISSUE TITLE
Typeahead Async: how to ignore undefined values?

### ISSUE THREAD

**Issue by bogacg** [valor-software/ngx-bootstrap#878] opened 2016-08-22 16:01 UTC
In example I'm working on, typeahead property is bound to an observable (async pipe) that gets objects from server.

Some of objects returned don't have property defined for typeaheadOptionField my typeahead bound to and that causes error like:
`Cannot read property 'toLowerCase' of undefined`

Because of this error options are not populated.

Is there a way to ignore returned objects with undefined option field and keep it working for the rest of returned objects.

Thanks

**Comment by adrianfaciu** [comment] 2016-08-23 05:56
This needs to be fixed in the code, not sure you can ignore it otherwise. You can use some easy workarounds in the meantime, for example defining a property that returns empty string if undefined or value if present.

**Comment by bogacg** [comment] 2016-08-23 09:10
This is what I've added to my observable call:

```
.take(1)
          .map(cps => {
            let keysArr = ['name','lastName','city'];
              for (let item of cps) {
                for( let key of keysArr)
                {
                  if(!item[key]){                 
                    item[key] = '';
                  }
                }
              }
              return cps;
          });
```

yet I'm still getting error `Cannot read property 'toLowerCase' of undefined` even though I see those 3 properties as empty string when I print cps to console.
Observable call is in constructor.

**Edit:** I've tried to subscribe this observable and bind typeahead to an array, still having issue.

**Edit 2:** Further debugging reveals that setting undefined properties to empty string is no different to let them undefined. Shall I set them to single space?
My personal view: it's better typeahead component handles this.

**Comment by adrianfaciu** [comment] 2016-08-23 16:43
I agree that the component should handle it. Was trying to help you find a workaround until that is fixed :smile: I'll try to have a look into the typeahead implementation. If you have time you can create a sample on how to reproduce this (just to make sure I won't miss something).

**Edit**: Could not reproduce using the latest version from development. But if you installed from npm there might be some changes that fixed this since .24 version. Anyhow, a sample on how to reproduce would clear this.

**Comment by bogacg** [comment] 2016-08-25 08:22
Yes I've installed it from npm.
As soon as I free some time I'd be happy to create a test project where you can see exactly what happens and play with it to hopefully find a fix, or I'll see if I can try it with dev branch.

**Comment by adrianfaciu** [comment] 2016-09-07 05:51
@bogacg You can try with the new official release, see if you still have this problem. Since I was not able to reproduce it, I assume it will work ok.

**Comment by adrianfaciu** [comment] 2016-10-04 18:38
This works fine in the latest release.

**Closed as completed by adrianfaciu** 2016-10-04 18:38 UTC
