### ISSUE TITLE
Daterangepicker initial value wrong pattern locale

### ISSUE THREAD

**Issue by jcebidanes** [valor-software/ngx-bootstrap#3108] opened 2017-11-24 18:36 UTC
Unfortunately not fix in beta9.
I try resolve add rangeInputFormat in bsconfig with palliative, but only work while I select date manualy.

Some settings are apparently only being applied after you have manually selected the date.

**My congif**
```
bsConfig = Object.assign({},
      {
        maxDate: new Date(),
        showWeekNumbers: false,
        rangeSeparator: ' || ',
        locale: 'ptBr',
        containerClass: 'theme-dark-blue',
        rangeInputFormat : 'DD-MM-YYYY'
      }
    );
```
Properties showWeekNumbers, locale and containerClass are applyed in load component. 
Properties maxDate, rangeSeparatorand and rangeInputFormat are applyed after I select manualy the date. 

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.9
Angular: 5.0.3
Build system: Angular CLI 1.5.2

**Comment by valorkin** [comment] 2017-11-25 19:29
I will be reworking setting locale, and working with initial vallues.i am completelly not happy with current implementation, plis composite components has race issues. I tried 3 diffferent approaches, but all sucks. So next week i will do DateAdapter for new and old datepickers

**Comment by valorkin** [comment] 2017-11-27 14:51
starting to work on this,
closing as duplicate of #2991

**Closed as completed by valorkin** 2017-11-27 14:51 UTC
Labels: comp(datepicker)
