### ISSUE TITLE
 How to set the selected page?  --pagination

### ISSUE THREAD

**Issue by markgzl** [valor-software/ngx-bootstrap#2176] opened 2017-07-10 03:07 UTC
When the page is initialized, set the page number is invalid.Is always the first page of the selected by default, even if my current setting of the third page

**Comment by dromadaire54** [comment] 2017-08-06 17:34
Hello everybody,

I want to know the situation of this issue because it's very annoying. When I retrieve the page number from the query parameter (URL) and I set it to the selected page. The page displayed is good but the page is marked as selected is always the first page. Please there's a workaround to fix quickly this problem. Thanks

**Comment by IlyaSurmay** [comment] 2017-11-08 12:04
Please recheck it on the latest version here https://valor-software.com/ngx-bootstrap/#/pagination
Also it would be much better if you'd provided plunkr/stackblitz with reproduction

You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IlyaSurmay** [comment] 2017-11-20 11:04
Closed as can't reproduce (v2.0.0-beta.8), will be reopened if we have sample to reproduce

**Closed as completed by IlyaSurmay** 2017-11-20 11:04 UTC
Labels: effort1: easy (hours), comp(pagination), can be closed?

**Comment by AleksandrBracyuk** [comment] 2019-12-04 21:11
...
this.items = result;
setTimeout(() => { this.currentPage = nextCurrentPage });
...
see https://blog.angular-university.io/angular-debugging/
"As we can see, we are using setTimeout() to defer this code to another Javascript Virtual Machine turn, and notice that we are not even specifying a value for the timeout."
