### ISSUE TITLE
Typeahead question

### ISSUE THREAD

**Issue by goekaypamuk** [valor-software/ngx-bootstrap#3069] opened 2017-11-18 13:46 UTC
Is it possible in typeahead to display a value of an object but save a key?

```
statesComplex: any[] = [
    { id: 1, name: 'Alabama', region: 'South' }
]
```

For example _name_ should be displayed in input box but the _id_ should be in the ngModel.

Thx in advance for any help

**Comment by IlyaSurmay** [comment] 2017-11-20 10:07
Duplicate of #2335.

**Closed as completed by IlyaSurmay** 2017-11-20 10:07 UTC
Labels: comp(typeahead)
