### ISSUE TITLE
Need to edit carousel template

### ISSUE THREAD

**Issue by Garima** [valor-software/ngx-bootstrap#2517] opened 2017-08-25 17:08 UTC
I need to edit the carousel template and use it in my project.

Using angular CLI build.Please tell me how to do

**Comment by IlyaSurmay** [comment] 2017-11-07 19:52
There's no functionality for now for editing predefined templates.

**Comment by IlyaSurmay** [comment] 2017-11-08 16:46
Closing this as a duplicate of #1727

**Closed as completed by IlyaSurmay** 2017-11-08 16:46 UTC
Labels: comp(carousel), can be closed?
