### ISSUE TITLE
Typeahead Async: TypeError: options.slice is not a function at TypeaheadDirective

### ISSUE THREAD

**Issue by ShakeySnake** [valor-software/ngx-bootstrap#2246] opened 2017-07-20 21:55 UTC
Hello, I'm trying to get the Typeahead Async module to work with my http datapull. I've mostly just copied the example but I'm getting this error.

Here is my http request sourced from an Angular2 service: 
```
getServices(term: string) {
        if (this.adalService.isLoggedIn) {
            var authHeader = "Bearer " + this.adalService.accessToken;
            var options = new RequestOptions({
                headers: new Headers({
                    'Accept': 'application/json',
                    'Authorization': authHeader
                })
            });
            
            return this.http.get(this.serviceTreeEndPoint + "?$filter=contains(Name, '" + term + "')", options)
                .map((response: Response) => <IServiceTree[]>response.json())
                .do(x => console.log(x))
        } else {
            console.log("ServiceTreeService: User Was Not Logged In");
        }
    }
```

Here is my component:
```
import { Component } from "@angular/core";
import { ServiceTreeService } from "../services/servicetree.service";
import { IServiceTree } from "../models/servicetree";
import { IServiceTreeMap } from "../models/servicetree.map";
import { TypeaheadMatch } from 'ngx-bootstrap/typeahead';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/of';

@Component({
    selector: "servicetreesearch",
    templateUrl: "./servicetreesearch.component.html"
})

export class ServiceTreeSearchComponent {

    asyncSelected: string = "";
    typeaheadLoading: Boolean;
    typeaheadNoResults: Boolean;
    dataSource: Observable<any>;

    constructor(private serviceTreeService: ServiceTreeService) {
        console.log("ServiceTreeSearchComponent")
        this.dataSource = Observable
      .create((observer: any) => {
        // Runs on every search
        observer.next(this.asyncSelected);
      })
      .mergeMap((term: string) => this.serviceTreeService.getServices(term));
    }

    public changeTypeaheadLoading(e: boolean): void {
        this.typeaheadLoading = e;
    }

    public changeTypeaheadNoResults(e: boolean): void {
        this.typeaheadNoResults = e;
    }

    public typeaheadOnSelect(e: TypeaheadMatch): void {
        console.log('Selected value: ', e.value);
    }
}

```
And this is the markup:
```
<input [(ngModel)]="asyncSelected"
         [typeahead]="dataSource"
         (typeaheadLoading)="changeTypeaheadLoading($event)"
         (typeaheadNoResults)="changeTypeaheadNoResults($event)"
         (typeaheadOnSelect)="typeaheadOnSelect($event)"
         typeaheadOptionsLimit="7"
         typeaheadOptionField="name"
         placeholder="Select a service"
         class="form-control">
  <div *ngIf="typeaheadLoading===true">
    <i class="glyphicon glyphicon-refresh ng-hide" style=""></i>
  </div>
  <div *ngIf="typeaheadNoResults===true" class="" style="">
    <i class="glyphicon glyphicon-remove"></i> No Results Found
  </div>
```

As soon as I type, the query executes and retrieves results from the API, followed immediately by the following error.

> ERROR TypeError: options.slice is not a function
    at TypeaheadDirective.webpackJsonp.../../../../ngx-bootstrap/typeahead/typeahead.directive.js.TypeaheadDirective.prepareMatches (typeahead.directive.js:263)
    at TypeaheadDirective.webpackJsonp.../../../../ngx-bootstrap/typeahead/typeahead.directive.js.TypeaheadDirective.finalizeAsyncCall (typeahead.directive.js:239)
    at SafeSubscriber._next (typeahead.directive.js:182)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next (Subscriber.js:185)
    at Subscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next (Subscriber.js:125)
    at Subscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next (Subscriber.js:89)
    at MergeMapSubscriber.webpackJsonp.../../../../rxjs/operator/mergeMap.js.MergeMapSubscriber.notifyNext (mergeMap.js:143)
    at InnerSubscriber.webpackJsonp.../../../../rxjs/InnerSubscriber.js.InnerSubscriber._next (InnerSubscriber.js:23)
    at InnerSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next (Subscriber.js:89)

**Comment by valorkin** [comment] 2017-07-21 05:40
ngx-bootstrap version?

**Comment by valorkin** [comment] 2017-07-21 07:40
1. duplicate of https://github.com/valor-software/ngx-bootstrap/issues/1290
2. issue happens when `term` is empty
this.serviceTreeService.getServices(term)
3. getServices should always return observable, `return Observable.empty()` could help

**Closed as completed by valorkin** 2017-07-21 07:40 UTC
