### ISSUE TITLE
Datepicker error when date manually entering

### ISSUE THREAD

**Issue by Sir-J** [valor-software/ngx-bootstrap#3461] opened 2018-01-16 07:05 UTC
**Date manually entering:**
![qip shot - screen 005](https://user-images.githubusercontent.com/12563410/34975792-0e9b45d4-fac6-11e7-9eb6-686019f0b5c3.png)

**When focus lost**

![qip shot - screen 006](https://user-images.githubusercontent.com/12563410/34975810-29430f66-fac6-11e7-863b-6a98f266647b.png)

**Comment by IlyaSurmay** [comment] 2018-01-16 10:16
Closing this as a duplicate of #2809

**Comment by IlyaSurmay** [comment] 2018-01-16 10:16
This will be fixed in the next release.

**Closed as completed by IlyaSurmay** 2018-01-16 10:16 UTC
