### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError in Pagination 

### ISSUE THREAD

**Issue by yzdedream** [valor-software/ngx-bootstrap#1936] opened 2017-04-25 16:56 UTC
So there is a long list to be displayed in pages. The list can also be filtered. When changing to a shorter filtered list, if the current page number is larger than the total pages number of the new list an error occurs.

[minimum reproduction code here in angular cli](https://github.com/yzdedream/paginationBugReproduce)

**Comment by vemuez** [comment] 2017-05-10 08:08
One workaround for that that's been floating around the internet is using `changeDetectorRef.detectChanges();` when the change happens. Although it will work, proably not a good idea to use I guess. Another issue, similar to this is in #406 - under what I've written. Plunkr and steps to reproduce are available too. Wasn't too sure whether to bring it up as a new issue or not.

**Comment by sam11385** [comment] 2017-06-19 17:13
I am getting the same issue on pretty much the same implementation.

**Comment by vlados** [comment] 2017-11-02 22:21
Is there fix for this?

**Comment by valorkin** [comment] 2017-11-03 00:27
@vlados I am sure folks were fixing similar issues, not sure with pagination
can you share error stack? ( so I can see which field cause issue)

**Comment by vlados** [comment] 2017-11-03 11:02
```
SearchComponent.html:9 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.
    at viewDebugError (core.es5.js:8433)
    at expressionChangedAfterItHasBeenCheckedError (core.es5.js:8411)
    at checkBindingNoChanges (core.es5.js:8575)
    at checkNoChangesNodeInline (core.es5.js:12416)
    at checkNoChangesNode (core.es5.js:12390)
    at debugCheckNoChangesNode (core.es5.js:13183)
    at debugCheckDirectivesFn (core.es5.js:13085)
    at Object.eval [as updateDirectives] (SearchComponent.html:9)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13067)
    at checkNoChangesView (core.es5.js:12230)
    at callViewAction (core.es5.js:12579)
    at execEmbeddedViewsAction (core.es5.js:12557)
    at checkNoChangesView (core.es5.js:12231)
    at callViewAction (core.es5.js:12579)
    at execComponentViewsAction (core.es5.js:12531)
    at checkNoChangesView (core.es5.js:12233)
    at callViewAction (core.es5.js:12579)
    at execEmbeddedViewsAction (core.es5.js:12557)
    at checkNoChangesView (core.es5.js:12231)
    at callViewAction (core.es5.js:12579)
    at execComponentViewsAction (core.es5.js:12531)
    at checkNoChangesView (core.es5.js:12233)
    at callViewAction (core.es5.js:12579)
    at execEmbeddedViewsAction (core.es5.js:12557)
    at checkNoChangesView (core.es5.js:12231)
    at callViewAction (core.es5.js:12579)
    at execComponentViewsAction (core.es5.js:12531)
    at checkNoChangesView (core.es5.js:12233)
    at callWithDebugContext (core.es5.js:13467)
    at Object.debugCheckNoChangesView [as checkNoChangesView] (core.es5.js:13014)
    at ViewRef_.checkNoChanges (core.es5.js:10182)
    at core.es5.js:4814
    at Array.forEach (<anonymous>)
    at ApplicationRef_.tick (core.es5.js:4814)
    at core.es5.js:4684
    at ZoneDelegate.invoke (zone.js:392)
    at Object.onInvoke (core.es5.js:3890)
    at ZoneDelegate.invoke (zone.js:391)
    at Zone.run (zone.js:142)
    at NgZone.run (core.es5.js:3821)
    at Object.next (core.es5.js:4684)
    at SafeSubscriber.schedulerFn [as _next] (core.es5.js:3635)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (core.es5.js:3621)
    at checkStable (core.es5.js:3855)
    at onLeave (core.es5.js:3934)
    at Object.onInvokeTask (core.es5.js:3884)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at ZoneTask.invokeTask (zone.js:499)
    at ZoneTask.invoke (zone.js:488)
    at timer (zone.js:2040)

View_SearchComponent_1 | @ | SearchComponent.html:9
-- | -- | --
  | DebugContext_.logError | @ | core.es5.js:13407
  | ErrorHandler.handleError | @ | core.es5.js:1080
  | (anonymous) | @ | core.es5.js:4819
  | ZoneDelegate.invoke | @ | zone.js:392
  | Zone.run | @ | zone.js:142
  | NgZone.runOutsideAngular | @ | core.es5.js:3844
  | ApplicationRef_.tick | @ | core.es5.js:4819
  | (anonymous) | @ | core.es5.js:4684
  | ZoneDelegate.invoke | @ | zone.js:392
  | onInvoke | @ | core.es5.js:3890
  | ZoneDelegate.invoke | @ | zone.js:391
  | Zone.run | @ | zone.js:142
  | NgZone.run | @ | core.es5.js:3821
  | next | @ | core.es5.js:4684
  | schedulerFn | @ | core.es5.js:3635
  | SafeSubscriber.__tryOrUnsub | @ | Subscriber.js:238
  | SafeSubscriber.next | @ | Subscriber.js:185
  | Subscriber._next | @ | Subscriber.js:125
  | Subscriber.next | @ | Subscriber.js:89
  | Subject.next | @ | Subject.js:55
  | EventEmitter.emit | @ | core.es5.js:3621
  | checkStable | @ | core.es5.js:3855
  | onLeave | @ | core.es5.js:3934
  | onInvokeTask | @ | core.es5.js:3884
  | ZoneDelegate.invokeTask | @ | zone.js:424
  | Zone.runTask | @ | zone.js:192
  | ZoneTask.invokeTask | @ | zone.js:499
  | ZoneTask.invoke | @ | zone.js:488
  | timer | @ | zone.js:2040
  | setTimeout (async) |   |  
  | scheduleTask | @ | zone.js:2056
  | ZoneDelegate.scheduleTask | @ | zone.js:411
  | onScheduleTask | @ | long-stack-trace-zone.js:117
  | ZoneDelegate.scheduleTask | @ | zone.js:405
  | onScheduleTask | @ | zone.js:301
  | ZoneDelegate.scheduleTask | @ | zone.js:405
  | Zone.scheduleTask | @ | zone.js:236
  | Zone.scheduleMacroTask | @ | zone.js:259
  | (anonymous) | @ | zone.js:2072
  | proto.(anonymous function) | @ | zone.js:1366
  | SearchComponent.ngOnInit | @ | search.component.ts:138
  | checkAndUpdateDirectiveInline | @ | core.es5.js:10843
  | checkAndUpdateNodeInline | @ | core.es5.js:12341
  | checkAndUpdateNode | @ | core.es5.js:12284
  | debugCheckAndUpdateNode | @ | core.es5.js:13141
  | debugCheckDirectivesFn | @ | core.es5.js:13082
  | (anonymous) | @ | SearchComponent_Host.html:1
  | debugUpdateDirectives | @ | core.es5.js:13067
  | checkAndUpdateView | @ | core.es5.js:12251
  | callViewAction | @ | core.es5.js:12599
  | execEmbeddedViewsAction | @ | core.es5.js:12557
  | checkAndUpdateView | @ | core.es5.js:12252
  | callViewAction | @ | core.es5.js:12599
  | execComponentViewsAction | @ | core.es5.js:12531
  | checkAndUpdateView | @ | core.es5.js:12257
  | callViewAction | @ | core.es5.js:12599
  | execEmbeddedViewsAction | @ | core.es5.js:12557
  | checkAndUpdateView | @ | core.es5.js:12252
  | callViewAction | @ | core.es5.js:12599
  | execComponentViewsAction | @ | core.es5.js:12531
  | checkAndUpdateView | @ | core.es5.js:12257
  | callWithDebugContext | @ | core.es5.js:13467
  | debugCheckAndUpdateView | @ | core.es5.js:13007
  | ViewRef_.detectChanges | @ | core.es5.js:10174
  | (anonymous) | @ | core.es5.js:4812
  | ApplicationRef_.tick | @ | core.es5.js:4812
  | (anonymous) | @ | core.es5.js:4684
  | ZoneDelegate.invoke | @ | zone.js:392
  | onInvoke | @ | core.es5.js:3890
  | ZoneDelegate.invoke | @ | zone.js:391
  | Zone.run | @ | zone.js:142
  | NgZone.run | @ | core.es5.js:3821
  | next | @ | core.es5.js:4684
  | schedulerFn | @ | core.es5.js:3635
  | SafeSubscriber.__tryOrUnsub | @ | Subscriber.js:238
  | SafeSubscriber.next | @ | Subscriber.js:185
  | Subscriber._next | @ | Subscriber.js:125
  | Subscriber.next | @ | Subscriber.js:89
  | Subject.next | @ | Subject.js:55
  | EventEmitter.emit | @ | core.es5.js:3621
  | checkStable | @ | core.es5.js:3855
  | onHasTask | @ | core.es5.js:3903
  | ZoneDelegate.hasTask | @ | zone.js:445
  | ZoneDelegate._updateTaskCount | @ | zone.js:465
  | Zone._updateTaskCount | @ | zone.js:289
  | Zone.runTask | @ | zone.js:209
  | drainMicroTaskQueue | @ | zone.js:602
  | ZoneTask.invokeTask | @ | zone.js:503
  | invokeTask | @ | zone.js:1540
  | globalZoneAwareCallback | @ | zone.js:1566
```

I found that if I set pagination.totalItems it's getting this error. I think is when the component enables the buttons.
I am using "ngx-bootstrap": "^2.0.0-beta.7"

**Comment by IlyaSurmay** [comment] 2017-11-10 14:47
Works fine in ngx-bootstrap@2.0.0-beta.8 - https://plnkr.co/edit/Z1NjZjsSfwX5PCeKz85a?p=preview
Closed as can't reproduce, will be reopened if we have sample to reproduce.

**Closed as completed by IlyaSurmay** 2017-11-10 14:47 UTC
Labels: effort2: medium (days), comp(pagination)
