### ISSUE TITLE
fix(modal): click function inside modal on internet explorer not working

### ISSUE THREAD

**Issue by fadelguy** [valor-software/ngx-bootstrap#2818] opened 2017-10-11 06:33 UTC
ngx-bootstrap: 1.9.3
Angular: 4.3.6

When i create a custom in my component and to a **click function from modal**, 
it's not on internet explorer 10+ but on chrome all working fine.
only the bsModalRef.hide() working on IE.

example:
<span class="redeem" (click)="updateCard()">update card </span> --> working only in chrome
<span class="close" (click)="bsModalRed.hide()">close</span> --> working also in IE

**Comment by IlyaSurmay** [comment] 2018-01-16 15:12
Closed as can't reproduce on latest version (2.0.0-rc.0) using this plunkr http://plnkr.co/edit/YMjLZVbUgaJ77F4uHriZ?p=preview

**Closed as completed by IlyaSurmay** 2018-01-16 15:12 UTC
Labels: comp(modal), needs: reproduce

**Comment by phreakadelle2k** [comment] 2018-10-19 06:42
I know this one is closed, but I'm having similar issues with modal dialogs.

I'm using version 3.0.1 of ngx-bootstrap in an Angular 6 (6.1.9) application created via Angular CLI.
The modal dialog is in its own component and is opened via BsModalService using something like this:

`this.modalService.show(ComponentName, { 'class': 'modal-xl', initialState });`

I have the bsModalRef inside the dialog component. The .hide() method is called in the click events of the buttons.

So, the dialog should close if I click on the X, the backdrop or the close- / save-button in the footer.
This works perfectly fine on any Firefox version, but on Internet Explorer 11 the dialog only closes when I click the backdrop.
