### ISSUE TITLE
Datepicker October Bug in Firefox

### ISSUE THREAD

**Issue by ZenGhost** [valor-software/ngx-bootstrap#1813] opened 2017-03-25 20:58 UTC
Every October, from the third week on, Datepicker keeps showing always the same day.
This happens on Firefox 52.0.1 (32-bit). On Chrome 56.0.2924.87 (64-bit) it worked as expected.
Tested on website:
https://valor-software.com/ng2-bootstrap/#/datepicker

![datepickerbug](https://cloud.githubusercontent.com/assets/22488444/24326035/299bb9ee-1184-11e7-9594-cf2cca010bf3.png)

**Comment by SergeyKuryatnick** [comment] 2017-03-28 12:23
Interesting, 
can't reproduce it on FF 52.0.1 (64-bit)

**Comment by gabrielgd** [comment] 2017-07-11 12:01
I can reproduce the bug on Firefox(54.0 (64-bit)), Ubuntu(16.04) and Timezone -3 GMT
![screenshot from 2017-07-11 08-57-52](https://user-images.githubusercontent.com/12735379/28067317-229a2f6c-6617-11e7-9951-fe2552d73408.png)

**Comment by gabrielgd** [comment] 2017-07-11 12:32
Fixed this bug by replacing `current.getDate()` with `current.getUTCDate()` in  daypicker.component.js line 93

**Comment by valorkin** [comment] 2017-08-22 11:53
fixed in
new datepicker (new style and pop up version)
available in v1.9.0+
check this out: http://valor-software.com/ngx-bootstrap/#/datepicker#examples

**Closed as completed by valorkin** 2017-08-22 11:53 UTC
Labels: comp(datepicker)
