### ISSUE TITLE
Dropdown collapses with dynamic content

### ISSUE THREAD

**Issue by Killmore** [valor-software/ngx-bootstrap#2029] opened 2017-06-03 13:55 UTC
If you add any content to the dropdown component after it initially expands, i.e. using *ngIf, it does not expand the 'hitbox' and treats and clicks within that dynamic content as the user clicking outside the dropdown. This in turn closes the drop down.

An example would be displaying a conditional datepicker for one of the dropdown items. The datepicker appears but selecting any date forces the dropdown to close. There are work arounds but it would be nice if the component could handle dynamic content better.

**Comment by IlyaSurmay** [comment] 2017-11-08 15:54
Dropdown can't take into account elements which are added to `body`, such as datepicker.
Please provide plunkr/stackblitz with reproduction if this is still relevant.
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IlyaSurmay** [comment] 2017-11-20 11:05
Closed as can't reproduce (v2.0.0-beta.8), will be reopened if we have sample to reproduce

**Closed as completed by IlyaSurmay** 2017-11-20 11:05 UTC
Labels: comp(dropdown), needs: reproduce, can be closed?
