### ISSUE TITLE
Datepicker (german format): When typing a date, it swaps the month and day on focusout. 

### ISSUE THREAD

**Issue by dave0688** [valor-software/ngx-bootstrap#3233] opened 2017-12-08 08:47 UTC
### Bug description:

I have a bsDatepicker in German locale. The datepicker functionality works as expected. However, when I type a date manually (e.g. 10.05.2017), the day and month get swapped on focusout. This is reproducible on the demo page as well:

https://valor-software.com/ngx-bootstrap/#/datepicker
Go to locales section and select "de". Then type a date and focusout.

### Plunker/StackBlitz that reproduces the issue:
No need for a plunker since it's reproducible on the demo page.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.8

Angular: 5.0.5

Bootstrap: 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed: 
AngularCLI

**Comment by IlyaSurmay** [comment] 2017-12-08 10:23
Closing this as a duplicate of https://github.com/valor-software/ngx-bootstrap/issues/2809

**Closed as completed by IlyaSurmay** 2017-12-08 10:23 UTC
Labels: comp(datepicker)
