### ISSUE TITLE
blur on typehead not working as expected

### ISSUE THREAD

**Issue by crh225** [valor-software/ngx-bootstrap#1550] opened 2017-01-24 19:26 UTC
https://plnkr.co/edit/OPb6LNL7ChYtunwb2g2L?p=preview

steps:
in textbox, type letter A. Click first item in list. blur gets called, and that makes sense. Click Alabama again, then input changes, but if you click outside the textbox, the blur event does not get fired again.

is there a way to re call blur after you the input value changes?

**Comment by cyberdante** [comment] 2017-08-25 17:01
Any progress on this issue?

**Comment by IlyaSurmay** [comment] 2017-11-09 15:55
Closed as can't reproduce (tested on version 2.0.0-beta.8 - https://plnkr.co/edit/CGByf7XpdzKCjnrnW9sx?p=preview), will be reopened if we have sample to reproduce.
You can use one of starter templates to reproduce:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Closed as completed by IlyaSurmay** 2017-11-09 15:55 UTC
Labels: comp(typeahead)

**Comment by bandhavya** [comment] 2018-07-11 10:50
this happens even now with customOptionsList template
