### ISSUE TITLE
How to invoke popover from div?

### ISSUE THREAD

**Issue by KellenHe** [valor-software/ngx-bootstrap#2355] opened 2017-08-04 01:58 UTC
`<div type="button" class="ti-info-alt" popover="Hello world" style="cursor: pointer; position: absolute; right: 3px; top: 3px; color: red;"></div>`
like this, it can not works.

`<button type="button" class="ti-info-alt" popover="Hello world" style="cursor: pointer; position: absolute; right: 3px; top: 3px; color: red;"></button>`
it is ok

how to invoke  popover from div ?

thanks

**Comment by IlyaSurmay** [comment] 2017-08-04 09:20
Couldn't reproduce this, works ok here - https://plnkr.co/edit/8cH50keR9QwpxjVVLTwF?p=preview

**Comment by IlyaSurmay** [comment] 2017-08-10 13:33
No updates, closing.

**Closed as completed by IlyaSurmay** 2017-08-10 13:33 UTC
Labels: comp(popover)

**Comment by KlausSchade** [comment] 2017-08-24 04:49
the plunkr you provided works fine 
but: when you use the attribute triggers="focus" only the button works and not the div

**Comment by KellenHe** [comment] 2017-08-24 05:35
thanks, i see.
