### ISSUE TITLE
Datepicker internalization

### ISSUE THREAD

**Issue by michaeljota** [valor-software/ngx-bootstrap#1075] opened 2016-10-04 20:27 UTC
Hi! 

I'm using momentjs to manage dates, but I've been unable to see a way to update the strings of the datapicker to use another language. Does the datepicker have support for i18n?

**Comment by valorkin** [comment] 2016-10-04 21:57
I am planning to release new version with i18n support for datepicker,
I will close this issue as a duplicate of https://github.com/valor-software/ng2-bootstrap/issues/455

when? ASAP

**Closed as completed by valorkin** 2016-10-04 21:57 UTC

**Comment by michaeljota** [comment] 2016-10-05 00:52
Thank you. :). I search before, but search just 'i18n' and 'internalization' ;-)

**Comment by chalcrow** [comment] 2018-07-04 00:18
This is now implemented in ngx-bootstrap. See https://valor-software.com/ngx-bootstrap/#/datepicker#locales. You can put something like this in your root module:

```
import { defineLocale } from 'ngx-bootstrap/chronos';
import { deLocale } from 'ngx-bootstrap/locale';
defineLocale('de', deLocale); 
```

Then in your root component you can do this:

```
import { BsLocaleService } from 'ngx-bootstrap';

constructor( private bsLocaleService: BsLocaleService ) { }

this.bsLocaleService.use('de')

```

This applies the German (de) locale for ngx-bootstrap across your application, by referencing the locale you've defined in the root module. This can be made dynamic, e.g. if you are storing the user's selected language in a service you can use the value from the service, and pass that to `bsLocaleService.use()`. You need to import the ngx-bootstrap/locale for every locale you want to support.

Only certain locales are supported in ngx-bootstrap. There is some info here http://bootstrap-datepicker.readthedocs.io/en/latest/i18n.html,  on creating a custom datepicker locale for bootstrap (although this info isn't specific to ngx-bootstrap).
