### ISSUE TITLE
Accordion: Strange behavior when changing isOpen from inside accordion-heading

### ISSUE THREAD

**Issue by MyCatOreo** [valor-software/ngx-bootstrap#1921] opened 2017-04-20 07:16 UTC
Using v 1.6.6

test.component.html:

    <accordion><button (click)="isOpen = !isOpen">Works fine</button>
        <accordion-group #realValue [isOpen]="isOpen">
            
            <div accordion-heading>
                <button (click)="isOpen = !isOpen">The first click doing nothing</button>
                <p>{{item}}</p>
                 {{realValue.isOpen}} {{isOpen}}
            </div>

            <button (click)="isOpen = !isOpen">Works fine</button>
            Content

        </accordion-group>
    </accordion>

test.component.ts:

    import { Component } from '@angular/core';
    @Component({
        selector: 'app-test',
        templateUrl: './test.component.html'
    })
    export class Test {
       isOpen: boolean;
       testList: string[]
       constructor() {
           this.testList = ['A', 'B', 'C'];
           this.isOpen = false;
       }
    }

I'm trying to add a button inside the accordion heading, so that when user clicks it, {{isOpen}} in the model can be switched on and off, and update the accordion as well.
But here's the problem...If I put the button is inside `<div accordion-heading>`, the first click always fails : the model is updated, but the accordion is not. From the second click onwards, both model and accordion can update. However they will have opposite value since the first click fails!
If the button is outside `<div accordion-heading>` then everything works ok. I can use some CSS to make it look like inside the heading, but that's certainly not the preferred solution...

Hmmm.....I don't understand why it behaves like this? Did I miss anything?

**Comment by artemvfrolov** [comment] 2017-05-29 10:24
took this issue

**Comment by artemvfrolov** [comment] 2017-06-01 09:40
can't reproduce this issue

**Comment by IlyaSurmay** [comment] 2017-11-08 15:44
Reproduced on latest version https://plnkr.co/edit/0uqY9713mnePtK2ew9BT?p=preview
We'll take a look at this.

**Comment by mbtakanov** [comment] 2017-11-21 16:39
I'm facing similar problem in my project. I've set [isOpen]="someCondition" in the accordion-heading div and when I make a simple click on the accordion-heading, super weird behavior is observed. I think it's because **isOpen and a simple mouse click are in conflict and each one of them executes its own function and at the end they overlap**.

**Comment by LimarenkoDenis** [comment] 2018-01-12 15:02
it still doesn't work correctly, unfortunately,
can you recommend the fast solution?

**Comment by IlyaSurmay** [comment] 2018-01-15 12:54
Ok, here's the thing. Accordion header itself has its own click handler that toggles the panel. So when you have `isOpen` binding inside accordion header, you're reassigning its value twice. Possible workarounds:
- using `$event.stopPropagation()` in click handler (https://plnkr.co/edit/T4dO3tNRJIvSUaLuJAA9?p=preview)
- using `isDisabled` deactivates internal click handler (but also makes panel grey)

**Closed as completed by IlyaSurmay** 2018-01-15 12:54 UTC
Labels: issue, effort2: medium (days), comp(accordion), prio: low
