### ISSUE TITLE
BSDatePicker input 

### ISSUE THREAD

**Issue by andrealegrottaglie** [valor-software/ngx-bootstrap#2827] opened 2017-10-12 10:04 UTC
I should use the following format dd / mm / yyyy. When initializing the date picker, the date is displayed in MM / dd / yyyy format.
How can I change this format?

The date is not formatted correctly at the init component
![image](https://user-images.githubusercontent.com/32734172/31490667-ff0e3a44-af44-11e7-8c3b-ed99d177e456.png)

After select date on date picker the date is formatted well
![image](https://user-images.githubusercontent.com/32734172/31490709-3034a2f2-af45-11e7-8bcd-66ca0b860524.png)

Help me please!!!!!
ngx-bootstrap: 1.9.3

Angular:4.3.4

Bootstrap:3

**Comment by pedroaraujo74** [comment] 2017-10-12 11:38
Duplicate of #2809

**Comment by valorkin** [comment] 2017-11-06 07:04
Closed as duplicate, will be implemented

**Closed as completed** 2017-11-06 07:04 UTC
Labels: comp(datepicker)
