### ISSUE TITLE
Tabset reverts to the first tab after hiding/showing with ngIf

### ISSUE THREAD

**Issue by itxdevs** [valor-software/ngx-bootstrap#1571] opened 2017-01-28 11:25 UTC
1. Create a simple tabset with 2 tabs
2. In tab 2 put a button that toggles a boolean variable tabsetVisible to false
3. Associate the tabsetVisible variable with ngIf
4. Create another button that toggles the boolean variable tabsetVisible true.
5. Click SHOW TABSET button to make the tabset visible
6. Switch to SENT tab
7. Click the HIDE TABSET button to hide the tabset
8. Now click the SHOW TABSET to make the tabset visible again

The tabset reverts to INBOX.

It is understandable that ngIf removes the element from dom and then reinserts and we assume that's why this behavior is happening but given that ngIf is the recommended way to manage visibility in Angular2, we think this needs to be addressed somehow.

The HTML snippet is below.

`<tabset *ngIf="tabsetVisible">
  <tab heading="Inbox">
    INBOX
  </tab>
  <tab heading="Sent">
    SENT
    <button (click)="tabsetVisible=false">HIDE TABSET</button>
  </tab>
</tabset>
<button (click)="tabsetVisible=true" *ngIf="!tabsetVisible">SHOW TABSET</button>`

**Comment by valorkin** [comment] 2017-01-31 10:46
may be add some `[isActive]` or `[isSelected]` to tab component

**Comment by IlyaSurmay** [comment] 2017-11-09 11:39
Closed as a duplicate of #823

**Closed as completed by IlyaSurmay** 2017-11-09 11:39 UTC
Labels: enhancement, question, comp(tabs)
