### ISSUE TITLE
Datepicker - style week-end days 

### ISSUE THREAD

**Issue by mrjohnr** [valor-software/ngx-bootstrap#4298] opened 2018-05-04 17:26 UTC
Hi

It is possible with datepicker to style week-end days (with red colors)?

also any chance to see a fix for this:  https://github.com/valor-software/ngx-bootstrap/issues/2922 ?
or adding the romanian locale: https://github.com/valor-software/ngx-bootstrap/pull/4205  ?
thanks

**Comment by valorkin** [comment] 2018-05-14 09:54
Romain locale published
Positioning fix will lend soon too :))
Closing as a duplicate of a note on my desktop :)))

**Closed as completed by valorkin** 2018-05-14 09:54 UTC

**Comment by mrjohnr** [comment] 2018-05-14 09:57
Hi. what about  style week-end days ?
thanks

**Comment by valorkin** [comment] 2018-05-14 10:45
I will get there, there are several things which overlap for this:
- is weekends disabled ( and how to process this in range picker)
- weekend styling
- is weekend in terms of locales

**Comment by mrjohnr** [comment] 2018-05-14 14:50
Indeed.found no class to hook for it

**Comment by jlavric** [comment] 2021-10-31 18:31
I have solved with this date custom classes.
https://valor-software.com/ngx-bootstrap/#/datepicker#date-custom-classes

```
    const currDay = new Date(now.getFullYear(), now.getMonth(), 1);

    for (let day = 0; day < 31; day++) {
      currDay.setDate(currDay.getDate() + 1);
      if (currDay.getDay() === 0 || currDay.getDay() === 6) {
        this.dateCustomClasses.push({ date: new Date(currDay), classes: ['text-danger'] });
      }
    }
```
![image](https://user-images.githubusercontent.com/6442636/139597184-95279115-78af-4458-87cc-10f56d478d9a.png)
