### ISSUE TITLE
Setup startingDay/first day of week to monday

### ISSUE THREAD

**Issue by sanka2701** [valor-software/ngx-bootstrap#2622] opened 2017-09-11 21:25 UTC
Hello,

I would like to ask how to set first day of the week to Monday. As I read through the library I can see that in the DatepickerConfig there is option to set up startingDay to something else as 0 (which defaults to Sunday).
However setting like:

<input class="form-control" placeholder="Datepicker" bsDatepicker **[startingDay]="1"** **[bsConfig]="options"** [minDate]="minDate" [maxDate]="maxDate" #dp="bsDatepicker">

gets me an error:
Can't bind to 'startingDay' since it isn't a known property of 'input'

and bsConfig has no such property as starting day or something similar.
Changing local does not effect this option. What am I missing ? Big thanks

**Comment by pgeyman** [comment] 2017-09-18 12:59
In the UK we quite often use Monday as the first day of the week in calendars, so this is quite an important feature.
Some other calendar/date components i've used link it into the locale too, so locale en-gb would automatically set the start day of the week value to Monday.

(I think that DatepickerConfig is the old datepicker component)

**Comment by pgeyman** [comment] 2017-09-18 13:15
In fact, looking at the ngx-bootstrap locale source, first day of the week is defined in locale, and in the en-gb locale, but it does not change the first day to Monday when you change the locale to en-gb on the demo page.

**Comment by frantisekjandos** [comment] 2017-09-22 09:08
We use Czech locale with first day Monday, which is defined in the locale file, but datepicker shows Sunday as first day anyway. We would appreciate, if this could be fixed.

**Comment by aakldey** [comment] 2017-09-27 14:22
same for ru locale

**Comment by felixeu31** [comment] 2017-10-01 10:59
same for es locale

**Comment by valorkin** [comment] 2017-10-02 14:16
fixed with #2330
should be available in `ngx-bootstrap@next`

**Comment by HugoMarteau** [comment] 2017-10-03 08:59
@valorkin I updated to ngx-bootstrap@next and still no changes even if I set locale fr. (language of day and months are ok but not the starting day)
angular : 4.3
angular-cli: 1.4.3
ngx-bootstrap: 2.0.0-beta.5
![image](https://user-images.githubusercontent.com/8122998/31117378-e9935ec8-a829-11e7-82e2-e75c334626a9.png)

**Comment by valorkin** [comment] 2017-10-03 11:52
Sorry I was closing a bunch of duplicated issue, to have clear roadmap. This issue is duplicate of older one, add starting day input is on roadmap

**Comment by SidekickJohn** [comment] 2017-10-23 07:57
@valorkin 
Is the said Roadmap visible anywhere? And could you please link the related Issue or re-open this one?

**Comment by valorkin** [comment] 2017-10-24 12:54
reproducible again

**Comment by valorkin** [comment] 2017-11-27 14:36
fixed once and for all  http://localhost:4200/#/datepicker#locales
:D

**Closed as completed by valorkin** 2017-11-27 14:36 UTC
Labels: comp(datepicker)

**Comment by pjarts** [comment] 2017-12-05 13:21
Will this be released as a bug fix to 1.9?

**Comment by joaogoya** [comment] 2018-02-07 17:21
Hello guys.
Not working for me

![datepicker](https://user-images.githubusercontent.com/31244900/35930962-84240b64-0c1a-11e8-8a0f-6c6aa0220100.jpg)

ngx bootstrap 2
angular 5

**Comment by ssharm02** [comment] 2018-05-22 15:55
has this been fixed?

**Comment by roblawford** [comment] 2018-06-19 13:13
Is this fixed guys?

**Comment by userAbhi** [comment] 2018-09-18 10:33
You can do this by changing dow:0 to dow:1 in 
ngx-bootstrap\chronos\locale\locale.defaults.js. in file.

eg: 
export var defaultLocaleWeek = {
//dow: 0
dow: 1,
// Sunday is the first day of the week.
doy: 6 // The week that contains Jan 1st is the first week of the year.
};

**Comment by AhsanAyaz** [comment] 2019-09-23 13:15
@valorkin I can't find how I can set the `startingDay` with `5.2.x`.
Any hints?

**Comment by lenichols** [comment] 2019-12-02 21:57
How do you set this in the current version?

**Comment by jkubiszewski** [comment] 2019-12-03 19:56
seriously?
https://valor-software.com/ngx-bootstrap/#/datepicker#locales
