### ISSUE TITLE
Datepicker - datepickerMode doesn't work

### ISSUE THREAD

**Issue by beabri** [valor-software/ngx-bootstrap#1524] opened 2017-01-19 18:21 UTC
[datepickerMode]="'year'" displays months and [datepickerMode]="'month'" displays days.
If I use [datepickerMode]="'year'" and click on one month, then windows with days opens, and that's not what I expect.

**Comment by valorkin** [comment] 2017-01-19 21:40
known issue, duplicate of another issue
working on it

**Closed as completed by valorkin** 2017-01-19 21:40 UTC

**Comment by beabri** [comment] 2017-01-20 10:30
Could you please give me the URL of the issue? Thanks.

**Comment by valorkin** [comment] 2017-01-20 10:43
I am not fixing current version, I already rewrote it from zero. Nearest week I am merging new Typeahead and then new datepicker

**Comment by ilacomp** [comment] 2017-03-01 21:08
Still not fixed. Could you please provide some info about when this functionality will be fixed?
