### ISSUE TITLE
Cannot use Modal-hack in hybrid ng1/ng2 application

### ISSUE THREAD

**Issue by danielnelin** [valor-software/ngx-bootstrap#1056] opened 2016-09-29 12:03 UTC
We are using ng-upgrade while migrating our application from Angular 1->2.

We're trying to use Modals in our ng2 components, but the required **hack** does not work in this context, since there is no root-level angular 2 component at the moment.

Tried adding a downgraded AppRoot-component in in the main ng1-template, but it is never added to `applicationRef.components` so it fails with _Cannot read property 'instance' of undefined_ in the ComponentsHelper

``` javascript
    ComponentsHelper.prototype.getRootViewContainerRef = function () {
        // The only way for now (by @mhevery)
        // https://github.com/angular/angular/issues/6446#issuecomment-173459525
        var appInstance = this.applicationRef.components[0].instance;
        if (!appInstance.viewContainerRef) {
            var appName = this.applicationRef.componentTypes[0].name;
            throw new Error("Missing 'viewContainerRef' declaration in " + appName + " constructor");
        }
        return appInstance.viewContainerRef;
    };
```

Is there any way around this for a hybrid app?

**Comment by valorkin** [comment] 2016-10-03 09:01
I will try another hack today, so most probably I will drop this viewContainerRef root dep

**Comment by jhhoff02** [comment] 2016-10-03 15:42
+1 Please try another hack, I still get the error: Cannot read property 'parentInjector' of undefined

**Comment by danielnelin** [comment] 2016-10-06 14:41
Hi, thanks for looking at this.
Unfortunately, I don't think this solves our problem.
The `applicationRef.components` is still empty, so i just fails in a different way.
Our issue is that almost all of our application is still angular 1, including root-parts.
I still don't see how I am supposed to use the ng2-hack, and without the hack, I guess there will never be a viewContainerRef to refer to? 

Maybe I'm just misunderstanding how I am supposed to get this working in hybrid-mode.
Did that work for you?

**Comment by valorkin** [comment] 2016-10-06 14:42
Give me a sample repo to reproduce, and I will drop a solution

**Comment by gios** [comment] 2016-10-07 13:10
Hi, everyone. As you wish, I added the temporary repository for testing this defect. Please notify me, if you will have some results about it.
[ng1-ng2-modal](https://github.com/gios/ng1-ng2-modal)

**Comment by valorkin** [comment] 2016-10-07 13:18
Awesome thanks!

**Comment by valorkin** [comment] 2016-10-10 11:17
cloning, it is time to fix this once and for all ;)

**Comment by valorkin** [comment] 2016-10-10 12:41
all possible hack points are empty for ngUpgrade

**Comment by gios** [comment] 2016-10-10 13:05
It's very bad news, do anyone have another ideas how to fix that and close the issue?

**Comment by valorkin** [comment] 2016-10-10 13:05
pss I am testing fix for it :)

**Comment by valorkin** [comment] 2016-10-10 13:08
this is how fix will looks like
https://github.com/gios/ng1-ng2-modal/pull/1/files

**Closed as completed** 2016-10-10 13:38 UTC

**Comment by danielnelin** [comment] 2016-10-11 09:04
Great!
We have verified that the latest version works in our hybrid-setup.
Thanks a lot for the fast resolution.
