### ISSUE TITLE
Subscribe to events in nested modal components

### ISSUE THREAD

**Issue by psined1** [valor-software/ngx-bootstrap#3006] opened 2017-11-08 22:58 UTC
Hi, I have nested modal components. My use case is such that I have a list of items, in which edit item activity may add another dependency.

The design:

Entity 1: productClass
Entity 2: product, links productClass

Component 1: shows list of products, clicking a product shows the first modal with Component 2

Component 2: shows product details, one of the properties is productClass, which has an option to add new productClass on the spot, clicking "add product class" calls out another child modal Component 3

Component 3: shows "add new product class"

After a new productClass was added, once Component 3 hides, I want Component 3 to communicate back to Component 2 the value of the new productClass just added and fill it in on the Component 2. After the new product was added, once Component 2 closes, I want Component 2 to communicate back to Component 1 the fact that new product was added and the list needs to be refreshed.

Hope this makes sense.

I tried to follow the Events example here -
https://valor-software.com/ngx-bootstrap/#/modals 

However that solution is based on subscription to onHide/onHidden event via the BsModalService. Therefore, should I subscribe to modalService.onHide event both in Component 1 and Component 2, not surprisingly, they both get triggered at the same time.

Is there a way to fire onHide for each modal individually?

**Comment by IlyaSurmay** [comment] 2017-11-09 10:00
Closing as a duplicate of #2917 
We'll figure something out about this, probably there will be an id identifying the modal or something like this.

**Closed as completed by IlyaSurmay** 2017-11-09 10:00 UTC
Labels: comp(modal)
