### ISSUE TITLE
Sortable  sometime show duplicate item text ?

### ISSUE THREAD

**Issue by firaskudsy** [valor-software/ngx-bootstrap#1678] opened 2017-02-22 21:20 UTC
after implementing the online sample for the Sortable Component, and when am trying drag and drop .. sometimes it show a duplicated text in the sortable-item 👍 

`TornadoTornado`

but the json under the sortable-wraper look ok !!

Any Idea why this is happening ?

**Comment by IlyaSurmay** [comment] 2017-11-09 10:41
Please provide plunkr/stackblitz with reproduction if this is still relevant.
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IlyaSurmay** [comment] 2017-11-13 10:52
Closed as can't reproduce (tested with ngx-bootstrap@2.0.0-beta.8), will be reopened if we have sample to reproduce

**Closed as completed by IlyaSurmay** 2017-11-13 10:52 UTC
Labels: needs: reproduce, comp(sortable), can be closed?
