### ISSUE TITLE
feat(tabs): add html content inside tabs using Array

### ISSUE THREAD

**Issue by talnagar** [valor-software/ngx-bootstrap#1265] opened 2016-11-24 11:39 UTC
Hello
I was wondering if it's possible to insert html content inside ng2-bootstrap tabs.
When I try it the html is displayed as text inside the tabs. 
thanks

**Comment by SergeyKuryatnick** [comment] 2016-11-24 14:01
Just use 
`<a>href="blablabla"</a>`

for example:
`
<tabset>
    <tab heading="Static title" ">
      <a href="blablabla">Static content</a> </tab>
</tabset>
`

**Comment by talnagar** [comment] 2016-11-27 06:05
Hi
thank you, it does work if I write each tab in the template explicitly. 
If I try and use an array of tabs displayed using an *ngFor, some of the content is ignored. 
I'm basing on the example in documentation: https://valor-software.com/ng2-bootstrap/#/tabs
In my code the id of the div is ignored:
typescript:
`tabs: Array<any> = [
        { title: 'Single Results - bushels per acre', content: ' <div id="lalala">lalala</div>', active: true, id: 'singles_bushels_per_acre' }
];
`
markup:
`  <tabset>
    <tab *ngFor="let tabz of tabs"
         [heading]="tabz.title"
         [active]="tabz.active"
         (select)="tabz.active = true"
         (deselect)="tabz.active = false"
         [disabled]="tabz.disabled"
         [removable]="tabz.removable"
         (removed)="removeTabHandler(tabz)"
         [customClass]="tabz.customClass"
         [innerHTML]="tabz?.content"
        >
    </tab>
  </tabset>`

**Comment by IlyaSurmay** [comment] 2018-01-16 11:29
Closed as a duplicate of #1487

**Closed as completed by IlyaSurmay** 2018-01-16 11:29 UTC
Labels: enhancement, comp(tabs)
