### ISSUE TITLE
keyup.enter doesn't fire inside a tab on IE

### ISSUE THREAD

**Issue by cygnosis** [valor-software/ngx-bootstrap#1999] opened 2017-05-24 15:31 UTC
Using Internet Explorer 11, if you place (keyup.enter)="f()" on an input inside a tab it will never fire in IE.  Works fine in Chrome.

**Comment by IlyaSurmay** [comment] 2017-11-08 15:58
Tested it in IE 11. works fine.
Please provide plunkr/stackblitz with reproduction if this is still relevant.
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IlyaSurmay** [comment] 2017-11-13 10:19
Closed as can't reproduce (IE 11, ngx-bootstrap@2.0.0-beta.8), will be reopened if we have sample to reproduce

**Closed as completed by IlyaSurmay** 2017-11-13 10:19 UTC
Labels: comp(tabs), needs: reproduce, can be closed?
