### ISSUE TITLE
ngx Bootstrap-ProgressBar not running properly

### ISSUE THREAD

**Issue by HafsaAsif** [valor-software/ngx-bootstrap#2009] opened 2017-05-30 11:23 UTC
Hi, 
I have tried ngx Bootstrap-ProgressBar from the link http://valor-software.com/ngx-bootstrap/#/progressbar, and follow the exact steps mentioned in it. 
1. Follow the same steps for import module class.
2. My component HTML file:
```
<progressbar [max]="max" [value]="dynamic">
  <span style="color:white; white-space:nowrap;">{{dynamic}} / {{max}}</span>
</progressbar>
``` 
3. My component TS file:
 ```
constructor(){
     this.random();
  }

  public max: number = 200;
  public showWarning: boolean;
  public dynamic: number;
  public type: string;

  public random(): void {
    let value = Math.floor((Math.random() * 100) + 1);
    let type: string;

    if (value < 25) {
      type = 'success';
    } else if (value < 50) {
      type = 'info';
    } else if (value < 75) {
      type = 'warning';
    } else {
      type = 'danger';
    }

    this.showWarning = (type === 'danger' || type === 'warning');
    this.dynamic = value;
    this.type = type;
  }
```
4. Display is attached in image file: Bad-display-progressbar.jpg

Progress works but partially not as smart as mentioned in demos in http://valor-software.com/ngx-bootstrap/#/progressbar.

Another issue is that, it is also not working for 'types'. Either I assign any type: danger, success, warning etc., it always show blue one.

My package.json is:
```
{
  "name": "test-asp-angular",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "core-js": "^2.4.1",
    "ngx-bootstrap": "^1.6.6",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-rc.1",
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typescript": "~2.0.0"
  }
}
```
![bad-display-progressbar](https://cloud.githubusercontent.com/assets/12494385/26581144/83f6b958-453b-11e7-901b-94a4b403ac51.jpg)

**Comment by valorkin** [comment] 2017-05-31 09:19
@HafsaAsif please show me generated html

like this
```html
<progressbar type="success">
    <div progress="" max="100" class="progress">
      <bar>
  <div aria-valuemin="0" class="progress-bar progress-bar-success" role="progressbar" style="min-width: 0px; width: 50%; transition: none;" aria-valuenow="50" aria-valuetext="50%">
          <b>50%</b>
      </div>
</bar>
    </div>
  </progressbar>
```

**Comment by johaven** [comment] 2017-06-02 12:32
+1 same problem
Progress not working and type too.
For information, version: 1.7.0, BS4 alpha 6, Angular 4.1.3
```html
<ul class="menu">
      <li>
        <a href="#" class="p-1">
          <span class="text-sm">No animation</span>
          <progressbar [value]="55" [max]="100" [type]="info">
            <span class="text-sm">55%</span>
          </progressbar>
        </a>
      </li>
       ...
```


<img width="748" alt="capture d ecran 2017-06-02 a 14 32 59" src="https://cloud.githubusercontent.com/assets/5459596/26725797/8367f170-47a0-11e7-9a57-3835149197cc.png">

<img width="280" alt="capture d ecran 2017-06-02 a 14 33 19" src="https://cloud.githubusercontent.com/assets/5459596/26725804/87034aaa-47a0-11e7-8db9-51693d184361.png">

**Comment by valorkin** [comment] 2017-06-02 13:55
template for bs4 is broken
duplicate of #1498

please add to enable bs4 theme
```
<body>
  <!-- Enable bootstrap 4 theme -->
  <script>window.__theme = 'bs4';</script>
```

**Comment by johaven** [comment] 2017-06-02 14:07
@valorkin bs4 theme is already enabled

**Comment by klstilling** [comment] 2017-06-12 12:43
Same issue here. bs4 theme enabled like @valorkin suggests. All the other components work fine.

**Comment by suparnavg** [comment] 2017-11-12 07:16
@johaven @klstilling did you manage to figure this out? I'm facing a similar issue wherein the progress bar div seems to be rendering but does not have any colours.

Generated HTML:
`<div aria-valuemin="0" class="progress-bar" role="progressbar" style="min-width: 0px; width: 68.33%;" ng-reflect-klass="progress-bar" ng-reflect-ng-style="[object Object]" aria-valuenow="41" aria-valuetext="68%"> ` 
        Progress
        </div>

Thank you!

**Comment by valorkin** [comment] 2017-11-12 07:27
With latest version ngx-bootstrap can guess your version of bootstrap css
Please provide plunker or stack blitz with issue reproduce

**Comment by suparnavg** [comment] 2017-11-12 07:36
Bootstrap version: v4.0.0-alpha.5
ngx-bootstrap version: 3.10.10

Just trying it out with this simple code but not working!
```
<progressbar class="progress" [value]="41" [max]="60"></progressbar>
```

Thank you for this fantastic library.

**Comment by valorkin** [comment] 2017-11-12 15:54
Version 3.10? Oo
Our latest is v2 beta.8

**Comment by suparnavg** [comment] 2017-11-12 17:13
Weird. Just rechecked and downloaded the v2 beta.8. Still facing the same issue,,

**Comment by valorkin** [comment] 2017-11-12 18:18
Can you create a plunker or stack blitz to reproduce?

**Comment by suparnavg** [comment] 2017-11-13 04:25
Here's a short plunkr (very simple trial implementation). I'll post a solution here in case I manage to figure it out. To reiterate I'm now using the v2 beta .8, bootstrap 4.0.0-alpha.5, and the other ngx bootstrap components I've used are working perfectly (tabs, typeahead, dropdown)

http://plnkr.co/edit/RPx4exanwRURfrVjtpf1?p=info

**Comment by suparnavg** [comment] 2017-11-24 14:37
There were styling issues with some of the classes which I've fixed in my external style sheet. Not sure why they occurred in the first place but have a working fix now.

**Closed as completed** 2017-12-04 21:03 UTC
Labels: question, comp(progressbar)
