### ISSUE TITLE
feat(typeahead): Add option not to select first when using typeahead component

### ISSUE THREAD

**Issue by vixriihi** [valor-software/ngx-bootstrap#3261] opened 2017-12-12 09:59 UTC
### feature request:

I could use a input in typeahead to disable autoselecting the first element from options

Something like @Input() typeaheadAutoSelectFirst = true so that it wouldn't break any existing implementations

**Comment by vixriihi** [comment] 2017-12-12 10:16
Ah there seems to be a pr already for this #1833.

**Comment by IlyaSurmay** [comment] 2018-01-16 15:10
Closed as a duplicate of #1281

**Closed as completed by IlyaSurmay** 2018-01-16 15:10 UTC
Labels: comp(typeahead)

**Comment by Rajanusa** [comment] 2018-11-17 00:29
Can any one explain how to implement not to select first by default.
I found someone suggested to override select event.
please suggest how to avoid selecting the first  when user is not selecting that.
