### ISSUE TITLE
Pagination fails if bound values change externally and not currently on page 1.

### ISSUE THREAD

**Issue by slubowsky** [valor-software/ngx-bootstrap#681] opened 2016-07-01 21:26 UTC
I have pagination defined like this:

```
<pagination [totalItems]="info.total" [(ngModel)]="info.page" [maxSize]="5" class="pagination-sm"
  [boundaryLinks]="true" [rotate]="false" (numPages)="numPages = $event" (pageChanged)="pageChanged($event)"></pagination>
```

I find that when I externally change the "info" object the pagination component fails with 
`browser_adapter.ts:82 ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: '[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]'. Current value: '[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]'`

this only happens if not viewing page 1 at the time of the change.
My "fix" for now is to call `ChangeDetectorRef.detectChanges()` when my info changes.

**Comment by jlberrocal** [comment] 2016-07-01 22:03
could you explain a little bit more your workaround? i'm having that issue but i don't know how to solve it

**Comment by slubowsky** [comment] 2016-07-03 03:07
@jlberrocal you just need to manually call change detection (or run in production mode)
You can do this by doing the following:

`import { ChangeDetectorRef } from '@angular/core';`

Have it injected into the constructor

`constructor(private _changeDetectionRef: ChangeDetectorRef) { }`

then after changing the object that is bound to your pagination component call the following:

`this._changeDetectionRef.detectChanges();`

**Comment by PRR24** [comment] 2016-07-14 15:06
@slubowsky The workaround seems to work well for totalItems binding, but does not work for itemsPerPage for weird reason.

**Comment by Draghonite** [comment] 2017-01-16 16:17
Where the detectChanges() call is made matters: I tried adding the detectChanges() call inside the changeFilter() function and it breaks paging where every other click resets the page back to 1.

I worked around it by ensuring that if the user intends to filter, the current page is first reset once; this happens on focus of the filter control.  Building on @slubowsky's approach, I:

1. Created a new function in the component TypeScript file:

```
public resetPage() {
    this.page = 1;
    this._changeDetectionRef.detectChanges();
}
```
2. Bound to this function in the component html:
```
<input ... (focus)="resetPage()" />
```

**Comment by setiseta** [comment] 2017-09-19 14:59
Is this bug only in development mode?
Gone in production mode?

**Comment by jlberrocal** [comment] 2017-09-19 17:17
@setiseta most probably because angular make a second validation only in dev mode, once you are running in production mode this should not happen, however is always recommended to fix it adding a workaround like detect changes on those cases

**Comment by IlyaSurmay** [comment] 2017-11-10 15:06
Works fine in ngx-bootstrap@2.0.0-beta.8 - https://plnkr.co/edit/Z1NjZjsSfwX5PCeKz85a?p=preview
Closed as can't reproduce, will be reopened if we have sample to reproduce.

**Closed as completed by IlyaSurmay** 2017-11-10 15:06 UTC
Labels: issue, comp(pagination)
