### ISSUE TITLE
typeahead: not selecting on click

### ISSUE THREAD

**Issue by rob-myers** [valor-software/ngx-bootstrap#403] opened 2016-04-13 13:24 UTC
Partial typing and pressing Enter works, but clicking on an item has no effect.

Can be verified at the typeahead demo i.e. http://valor-software.com/ng2-bootstrap/#typeahead

**Comment by rbaarsma** [comment] 2016-04-13 13:29
:+1:

The problem seems to lie in the onBlur() event. I guess it fires simultanously and inside the hide() function the container gets disposed(). 

For now I've hotfixed it in the pull request with a timeout, which is not really noticable, but does fix the issue and allowing the click event to fire first as intended.

``` typescript
  // typeahead.directive.ts

  @HostListener('blur', ['$event.target'])
  protected onBlur(target:any):void {
    setTimeout(() => this.hide(), 250);
  }
```

If anyone has a better solution feel free to implement, but this is an annoying and breaking bug, so it would be great if this pull request can be merged asap.

**Comment by slintes** [comment] 2016-04-13 14:00
this is fixed already, see https://github.com/valor-software/ng2-bootstrap/issues/363 and https://github.com/valor-software/ng2-bootstrap/pull/398

**Closed as completed** 2016-04-15 13:30 UTC
