### ISSUE TITLE
Datepicker internalization

### ISSUE THREAD

**Issue by BeejeeDS** [valor-software/ngx-bootstrap#2126] opened 2017-06-26 08:31 UTC
I know there are a lot of issues concerning this topic.
In each issue you mention that this feature will be added soon.

- [#455](https://github.com/valor-software/ngx-bootstrap/issues/455)
- [#1107](https://github.com/valor-software/ngx-bootstrap/issues/1107)
- ...

Is this feature already available in the current version?
If that is the case, can you show me how I change the culture/labels of the datepicker?
I couldn't find anything in the current documentation...

**Comment by BeejeeDS** [comment] 2017-07-06 07:19
?

**Comment by krzSobin** [comment] 2017-08-02 09:03
+1

**Comment by IlyaSurmay** [comment] 2017-08-11 14:59
Duplicate of #455

**Closed as completed by IlyaSurmay** 2017-08-11 14:59 UTC
Labels: comp(datepicker)
