### ISSUE TITLE
tooltip with html

### ISSUE THREAD

**Issue by vmironovs** [valor-software/ngx-bootstrap#721] opened 2016-07-12 07:53 UTC
Why this don`t come to 1.0.20???

**Comment by Dinistro** [comment] 2016-07-12 08:06
@vmironovs Because it's not implemented right now. There is a PR #562 but it's not complete. If you really need this, we would be happy about an PR.

**Comment by vmironovs** [comment] 2016-07-12 08:06
thx. i change it manuali

**Comment by Dinistro** [comment] 2016-07-12 08:07
duplicate of #474

**Closed as completed by Dinistro** 2016-07-12 08:07 UTC
