### ISSUE TITLE
Expression has changed after it was checked.

### ISSUE THREAD

**Issue by chintan3100** [valor-software/ngx-bootstrap#1234] opened 2016-11-12 12:05 UTC
Expression has changed after it was checked. Previous value: '1'. Current value: '2'.
Is any one found solution for that. ?. This issue will come when we are on second page and total record is 20 and record/page=10. Now if i change total record to 7. We will get issue.Expression has changed after it was checked. Previous value: '1'. Current value: '2'.

**Comment by bocher** [comment] 2016-11-15 03:22
i had  the same situation

**Comment by wilfredmifsud** [comment] 2016-11-23 11:14
+1

**Comment by Boichenko** [comment] 2016-12-12 17:00
+1

**Comment by IlyaSurmay** [comment] 2017-11-10 12:34
Could someone create a plunkr/stackblitz that reproduces this issue?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IlyaSurmay** [comment] 2017-11-10 14:36
Works fine in ngx-bootstrap@2.0.0-beta.8 - https://plnkr.co/edit/Z1NjZjsSfwX5PCeKz85a?p=preview
Closed as can't reproduce, will be reopened if we have sample to reproduce.

**Closed as completed by IlyaSurmay** 2017-11-10 14:36 UTC
Labels: comp(pagination), needs: reproduce, can be closed?
