### ISSUE TITLE
Typeahead Reactive Forms Issue in IE 11 for Item Selections

### ISSUE THREAD

**Issue by mukesh-k** [valor-software/ngx-bootstrap#4019] opened 2018-03-16 18:16 UTC
Typeahed for reactive forms breaks for item selections, every first attempt. This issue is reproducible on Internet Explorer 11 and also can be seen on official documentation link below

https://valor-software.com/ngx-bootstrap/#/typeahead#reactive-forms.

1. Go to reactive forms section.
2. Since typeaheadMinLength is set to 0, as soon the focus goes to the control, default list pops down.
3. Select an item from the list. the very first attempt to select fails, works 2nd time if repeated.

You can filter results by typing some text and then clear off the entire field. and repeat the same process above.

Version 1.9.3 Works fine, in case it needs to be compared with new version >2.0.0.

**Comment by IlyaSurmay** [comment] 2018-03-19 10:00
Closed as a duplicate of #3124

**Closed as completed by IlyaSurmay** 2018-03-19 10:00 UTC
Labels: comp(typeahead), duplicate

**Comment by mukesh-k** [comment] 2018-03-19 12:14
Thanks, However, #3124 - doesn't provide a fix? Do we have a fix for this?
