### ISSUE TITLE
issue: modal backdrop component still displayed

### ISSUE THREAD

**Issue by eliavmaman** [valor-software/ngx-bootstrap#2124] opened 2017-06-25 13:11 UTC
we are using angular-cli 1.0.0 lately we upgrade the  angular/animations:4.0.0-rc.3, TO
 angular/animations - ^4.0.0      and those as well :
 angular/platform-browser - ^4.0.0
angular/platform-browser-dynamic - ^4.0.0, 

now  when the modal is closed  ,the modal itself disappear but the  backdrop component still displayed.

We have to solve it asap, can u please help us?

**Comment by eliavmaman** [comment] 2017-06-25 13:21
anyone?

**Comment by eliavmaman** [comment] 2017-06-26 06:20
one more thing ,I've noticed that every time the modal is opened new bs-modal-backdrop component is added.
![image](https://user-images.githubusercontent.com/6911449/27517306-fcdee998-59d2-11e7-9126-84f6d9f81b16.png)

**Comment by valorkin** [comment] 2017-06-28 15:28
can not reproduce, is it still an issue?

**Comment by tonghia** [comment] 2017-07-07 06:39
hi, can you show your open modal code, I met the same problems because my open modal function inside an observable subscribe, and I forgot to unsubscribe when the app removed that component.

**Comment by valorkin** [comment] 2017-07-07 11:20
Closing for now, because I can not reproduce it

**Closed as completed by valorkin** 2017-07-07 11:20 UTC
Labels: issue, comp(modal)
