### ISSUE TITLE
Feature Request: Keyboard Support for Accordion

### ISSUE THREAD

**Issue by markleppke** [valor-software/ngx-bootstrap#3034] opened 2017-11-13 22:35 UTC
Current accordion UI appears to not be able to accessible via the keyboard, when I tab through an interface, the example, or in my app, the tab bypasses the accordion headers. It would be expected that a user could access by tabbing through the headers then use 'enter' to open that panel. 

Thanks! I'd look at contributing, but I'm an UX Designer, and not skilled enough with JavaScript to really help here without making a mess of things.

**Comment by IlyaSurmay** [comment] 2017-11-14 12:12
Closing as a duplicate of #1675

**Closed as completed by IlyaSurmay** 2017-11-14 12:12 UTC
Labels: comp(accordion)
