### ISSUE TITLE
Dynamic Component creation helper a service

### ISSUE THREAD

**Issue by robbaman** [valor-software/ngx-bootstrap#1009] opened 2016-09-20 21:21 UTC
Sorry if this is a bad question, I'm just now starting with Angular 2 so all my experience comes from Angular 1 (and the ui-bootstrap plugin for that).

Is there any way to create a modal from a service like you can with ui-bootstrap? The examples all have the template for the modal as part of a component, but I often have something like a confirmation service where you inject the service and can then just call confirmSvc.Confirm('title', 'question').then(result => ....)

Since the html for this confirmatino dialog is always the same I'd hate to have to include it on every component that uses it. Furthermore I sometimes have services that as part of their operation ask for confirmation. If the dialog always has to be on a component I'd have to pass the dialog reference around to the service which seems much less very convenient to me than being able to inject the confirmation service and have it somehow create it's own UI as part of it's internal operation.

**Comment by kokokenada** [comment] 2016-09-24 22:39
No way to do it. There were a couple of work arounds in https://github.com/valor-software/ng2-bootstrap/issues/579 which don't work anymore.  And this might help: http://blog.lacolaco.net/post/dynamic-component-creation-in-angular-2-rc-5/.  

@valorkin - what is the plan for launching modals?  Putting modal definitions in the parent is a problem in my humble opinion.  Also are you tracking Material? https://github.com/angular/material2/issues/114, https://github.com/angular/material2/tree/master/src/lib/dialog

**Comment by robbaman** [comment] 2016-09-25 10:15
Note that if it's an existing component you can actually add it dynamically. See this stackoverflow Q/A for details on how to do it. It seems that with some modification it should be possible to create a service/directive combination that allows you to call `ShowComponentAsDialog()` or something.

http://stackoverflow.com/questions/39685125/angular-2-0-final-how-to-instantiate-a-component-from-code

**Comment by valorkin** [comment] 2016-09-25 10:22
Like components helper service? Check utilise folder

**Comment by robbaman** [comment] 2016-09-25 10:34
Yes exactly. Hadn't seen that helper service. Since @kokokenada mentioned it wasn't possible to create and add a component (or I may understand him/wrong) I figured I'd share my experiences.

As both me and @kokokenada mentioned though, the current example of how to work with modals isn't really ideal. It requires you to add the modal content to the parent component while oftentimes that just isn't what you want. Being able to launch a modal from the modalservice specifying the component type to show in the modal seems much better to me. 

These techniques should make that possible shouldn't they?

**Comment by dicbrus** [comment] 2016-09-29 09:54
You can place modal into separate child component.

After you can access this 'child modal component' from parent component with @ViewChild, you can run it's show/hide methods, etc

If you need I'll place some code here or will prepare plunker to show it.

**Comment by robbaman** [comment] 2016-09-29 10:29
Let's say I have a CustomerPicker dialog that can be used to select a customer. Now in my application there may be dozens of places where a customer may be selected. I'd like to be able to create a CustomerPickerService that has a `SelectCustomer` function to get one or more customers.

In Angular1, this service would be entirely responsible for managing the UI that is required for picking a customer. In this new approach I'd have to add the child component to every component that potentionally shows the dialog. This just seems a bit backwards. Especially if you consider that the CustomerPickerService could potentially also be used from other services.

**Comment by dicbrus** [comment] 2016-09-29 12:15
From my point of view for such Picker the best solution is component , it is reusable, and can be used for whole application, can include all needed business logic, etc...

**Comment by valorkin** [comment] 2016-10-13 20:58
@robbaman hey, I got your idea, and I like
basically it is not about modal at all,
it is more about dynamic components

duplicate of #579

**Comment by valorkin** [comment] 2016-12-21 23:56
Check component loader

**Closed as completed by valorkin** 2016-12-21 23:56 UTC
