### ISSUE TITLE
Pagination current page not updating

### ISSUE THREAD

**Issue by slubowsky** [valor-software/ngx-bootstrap#1600] opened 2017-02-03 15:15 UTC
Don't know if its new or I just never noticed but binding to pagination using ngModel - [(ngModel)]="currentPage" pagination is not updated when currentPage changes. (Other values such as totalPages are working. I see check_totalItems being called and it sets totalItems to the new value, which in turn sets the page - to the old selected page, not the new one that should be coming in)

My workaround for now is to get the PaginationComponent as a ViewChild and manually call this.pagination.page = currentPage

Version info:
ng2-bootstrap: 1.3.2

@angular/cli: 1.0.0-beta.30
node: 7.5.0
os: win32 x64
@angular/common: 4.0.0-beta.6
@angular/compiler: 4.0.0-beta.6
@angular/core: 4.0.0-beta.6
@angular/forms: 4.0.0-beta.6
@angular/http: 4.0.0-beta.6
@angular/platform-browser: 4.0.0-beta.6
@angular/platform-browser-dynamic: 4.0.0-beta.6
@angular/router: 4.0.0-beta.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 4.0.0-beta.6
@ngtools/webpack: 1.2.4

**Comment by geekrumper** [comment] 2017-02-14 14:59
I have the same request, and had to adapt your workaround. thx...

**Comment by valorkin** [comment] 2017-02-15 23:20
is it in ng v4+ or with ng v2.4+ too?

**Comment by slubowsky** [comment] 2017-02-16 03:59
I get the same bug with ng v2.4.7.

**Comment by EinarValholl** [comment] 2017-03-17 11:21
1 hour being spent for so simple solution

`<pagination [totalItems]="totalItems" [(ngModel)]="activePage"></pagination>

@Input() activePage;

ngOnChanges() {
        if(!!this.activePage) {
            this.setPageFromRoute = true;
            this.activePage = parseInt(this.activePage); // binding value does not convert type string to type number automatically, so You must do it manually 
        }
    } 
`

**Comment by niklissad** [comment] 2017-05-23 09:59
I have some issue too, just be sure that type of currentPage is number
`this.pagination.page = parseInt(currentPage)`

**Comment by IlyaSurmay** [comment] 2017-11-09 11:27
Is this still present in latest version 2.0.0-beta.8 ? I checked it and it works fine.

**Comment by valorkin** [comment] 2017-11-09 11:34
Closed as can't reproduce, will be reopened if we have sample to reproduce

**Closed as completed by valorkin** 2017-11-09 11:34 UTC
Labels: comp(pagination), can be closed?

**Comment by slubowsky** [comment] 2017-11-09 15:42
@valorkin Bug is still there in 2.0.0-beta.8. Not bothering me much as I have a simple enough work around. 

I bind to totalItems, itemsPerPage and then page using ngModel. I update all 3 at once and my page update is ignored (I dont doubt that alone it probably works, its when the other fields are modified along with it that the change gets lost)

```
<pagination [totalItems]="info.total" [(ngModel)]="info.page" [maxSize]="5" class="pagination-sm"
 [boundaryLinks]="true" [rotate]="false" (pageChanged)="pageChanged($event)" [itemsPerPage]="info.perPage">
</pagination>
```

change all 3 values on info and then call `this.changeDetectorRef.markForCheck();`. Page will stay at old value

**Comment by NishantMadkikar** [comment] 2018-07-04 08:02
I am same problem with angualr 5 i am giving value to the current page but it is setting always to 1
