### ISSUE TITLE
Typeahead exact string Match

### ISSUE THREAD

**Issue by ObaidUrRehman** [valor-software/ngx-bootstrap#1567] opened 2017-01-27 12:47 UTC
Is it possible to do exact match on items in the typeahead directive? I have the following items in my list:

`items = [ 
'${test_url}', 
'${test_name}'
........];`

I want the suggestion to appear only when the user types `$`. Right now it also appears if the user types `test`.

**Comment by valorkin** [comment] 2017-01-31 21:39
it is more like contains match with begins with match
planned feature
closing this as duplicate of https://github.com/valor-software/ng2-bootstrap/issues/1513

**Closed as completed by valorkin** 2017-01-31 21:39 UTC
Labels: comp(typeahead)
