### ISSUE TITLE
BsModalService with Dynamic Injection

### ISSUE THREAD

**Issue by ceoaliongroo** [valor-software/ngx-bootstrap#2637] opened 2017-09-13 08:11 UTC
Hi, 

I have three component `Child` extend from a Component `Parent`. 

I'll try to inject `BsModalService` in the parent component using the constructor, but i received and Error message  `super() `  because is missing the BsModalService parameter.

How i cal solve it?

I tried to use  `ReflectiveInjector`or the new `StaticInjector` or a simple `new BsModalService` but i could not figure out,  how to get and pass the parameter `ComponentLoaderFactory` 

Please, i need your help

**Comment by IlyaSurmay** [comment] 2017-09-13 13:18
Could you create a plunkr? That would help us to find out where the issue is.

**Comment by valorkin** [comment] 2017-11-06 08:03
Hey, I am grooming issues, and closing this one.
As soon as we get reproducible sample, we will reopen it

**Closed as completed by valorkin** 2017-11-06 08:03 UTC
Labels: comp(modal)
