### ISSUE TITLE
How to apply animation to Alert?

### ISSUE THREAD

**Issue by sanket360** [valor-software/ngx-bootstrap#1149] opened 2016-10-22 13:14 UTC
I would like to apply animation (fade-in and fade-out effects) to ng2-bootstrap alert. Is there any sample available to achieve this functionality?

**Comment by valorkin** [comment] 2017-03-02 13:45
I am afraid that animation will be added when v4 will come stable
and animation will came as separate package

**Comment by IlyaSurmay** [comment] 2017-11-10 12:47
Closing as a duplicate of #801

**Closed as completed by IlyaSurmay** 2017-11-10 12:47 UTC
Labels: comp(alerts)
