### ISSUE TITLE
pageChanged fire on ngModel !=1

### ISSUE THREAD

**Issue by euprogramador** [valor-software/ngx-bootstrap#1980] opened 2017-05-15 15:26 UTC
in pagination component, when currentPage is 2 or high, pageChanged is fired without page change.

**Comment by IlyaSurmay** [comment] 2017-11-08 16:04
Please provide plunkr/stackblitz with reproduction if this is still relevant.
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IlyaSurmay** [comment] 2017-11-13 10:19
Closed as can't reproduce (tested with ngx-bootstrap@2.0.0-beta.8), will be reopened if we have sample to reproduce

**Closed as completed by IlyaSurmay** 2017-11-13 10:19 UTC
Labels: comp(pagination), needs: reproduce, can be closed?
