### ISSUE TITLE
Is it possible to set default time to nothing in TimePicker?

### ISSUE THREAD

**Issue by windians** [valor-software/ngx-bootstrap#2647] opened 2017-09-13 19:18 UTC
I am using the timepicker component. Below is my HTML for it:
` <timepicker id="txtScheduledTime" name="txtScheduledTime" [(ngModel)]="model.ScheduledTime"></timepicker>`

Right now what happens is by default even when model.ScheduledTime comes back NULL the timepicker shows current time. Is there a way to null it out so when no time is coming back from the web request? I looked through Timepicker config located at [](https://valor-software.com/ngx-bootstrap/#/timepicker) but could not find what I am looking for here. Please write back here if any other explanation is needed. Thanks!

**Comment by windians** [comment] 2017-09-13 19:19
For some reason I could not paste the link where I was looking at timepicker config but here it is: https://valor-software.com/ngx-bootstrap/#/timepicker

**Comment by windians** [comment] 2017-09-14 20:12
An update to my issue. So I installed the latest ngx bootstrap using npm install ngx-bootstrap. This takes care of my initial bug where blank time is displayed as HH:MM. Which is great. 
**BUT I am facing another issue.** When I tab in and type time in time my model is not binded. But when I select time using up and down arrows then it binds the time. Why is that and how do I fix this ?
Please reply soon.

**Comment by windians** [comment] 2017-09-15 20:11
@valorkin Do you have anything on this ? Your input will be greatly appreciated. When I tab into timepicker and type in times it it does not bind time to model. But when I use arrow up and down keys it does.

**Comment by valorkin** [comment] 2017-09-15 20:53
@windians sounds like an issue to me

**Comment by windians** [comment] 2017-09-18 12:13
Do you recommend me to try something else ? @valorkin

**Comment by IlyaSurmay** [comment] 2017-11-07 11:16
@windians Hi, could you reproduce this issue in plunkr/stackblitz?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

works ok on latest version (2.0.0-beta.8) https://valor-software.com/ngx-bootstrap/#/timepicker

**Comment by valorkin** [comment] 2017-11-09 17:09
Closing for now, cuz can't reproduce, seems to be working fine

**Comment by timaxapa** [comment] 2017-11-10 08:14
@valorkin 
1.9.3 had this issue - [Plunker](https://plnkr.co/edit/C5Sgi87PtmtEbRXKvm7l?p=preview)

And one more issue: when I change hours and minutes manually - model is not updates
![2017-11-10_12-27-04](https://user-images.githubusercontent.com/9010313/32649206-a16c48ba-c612-11e7-95c8-867bbecd7497.gif)

**Comment by valorkin** [comment] 2017-11-10 11:29
Between v1.9.3 and latest ~100 commits, plus I have seen PR with similar description for sure

**Comment by IlyaSurmay** [comment] 2017-11-20 11:06
Closed as can't reproduce (v2.0.0-beta.8), will be reopened if we have sample to reproduce

**Closed as completed by IlyaSurmay** 2017-11-20 11:06 UTC
Labels: comp(timepicker), needs: reproduce, can be closed?

**Comment by timaxapa** [comment] 2017-11-20 12:42
@IlyaSurmay 
[Plunker](https://plnkr.co/edit/PBPMNb7mN9QZXrv61mrx?p=preview) v2.0.0-beta.8
