### ISSUE TITLE
Tooltip not working on Angular 4.0.0-rc.2: Cannot read property 'def' of undefined

### ISSUE THREAD

**Issue by exequiel09** [valor-software/ngx-bootstrap#1710] opened 2017-03-04 23:34 UTC
### Stack Trace

```
TypeError: Cannot read property 'def' of undefined
    at new DebugContext_ (core.es5.js:13942)
    at getCurrentDebugContext (core.es5.js:14126)
    at DebugRendererV2.createText (core.es5.js:14228)
    at RendererAdapter.createText (core.es5.js:11554)
    at ComponentLoader._getContentRef (component-loader.class.js:159)
    at ComponentLoader.show (component-loader.class.js:64)
    at showTooltip (tooltip.directive.js:175)
    at TooltipDirective.show (tooltip.directive.js:183)
    at show (tooltip.directive.js:144)
    at HTMLElement.<anonymous> (platform-browser.es5.js:3802)
    at ZoneDelegate.invokeTask (zone.js:363)
    at Object.onInvokeTask (core.es5.js:4381)
    at ZoneDelegate.invokeTask (zone.js:362)
    at Zone.runTask (zone.js:166)
    at HTMLElement.ZoneTask.invoke (zone.js:416)
```

### Versions

```
@angular/common: 4.0.0-rc.2
@angular/compiler: 4.0.0-rc.2
@angular/core: 4.0.0-rc.2
@angular/forms: 4.0.0-rc.2
@angular/http: 4.0.0-rc.2
@angular/platform-browser: 4.0.0-rc.2
@angular/platform-browser-dynamic: 4.0.0-rc.2
@angular/router: 4.0.0-rc.2
ng2-bootstrap: 1.3.3
```

**Comment by valorkin** [comment] 2017-03-07 13:54
it will be supported in version 2
duplicate of https://github.com/valor-software/ng2-bootstrap/issues/1692

**Closed as completed by valorkin** 2017-03-07 13:54 UTC
