### ISSUE TITLE
Datepicker Locale en-gb does not work

### ISSUE THREAD

**Issue by markpritchett** [valor-software/ngx-bootstrap#2702] opened 2017-09-20 18:03 UTC
See screenshot below:

https://valor-software.com/ngx-bootstrap/#/datepicker#locales
![image](https://user-images.githubusercontent.com/1267889/30659621-440050e4-9e36-11e7-9f9b-f4842c422239.png)

It should be **20/09/2017**.

**Comment by pgeyman** [comment] 2017-09-21 10:43
Related issues: #2622, #2694, #2699

**Comment by valorkin** [comment] 2017-10-02 14:17
yes, duplicate of #2622 and #2694 
fixed with #2360

**Closed as completed by valorkin** 2017-10-02 14:17 UTC
Labels: comp(datepicker)

**Comment by cyberabis** [comment] 2017-10-08 11:36
Hi, which release version should I pull to get this fix? 

Even in 2.0.0-beta.6, only on clicking the dates the format is right. It's incorrect when the initial value is set or when typing into the input.

**Comment by valorkin** [comment] 2017-10-08 13:17
Post formatting user input is not part of current implementation, you can do a feature request for it

**Comment by m1t0k** [comment] 2018-01-07 11:38
Works in 2.0.0-beta.10, but doesn't work in 2.0.0-rc.0.
