### ISSUE TITLE
Datepicker not validate correct dateInputFormat

### ISSUE THREAD

**Issue by fchiumeo** [valor-software/ngx-bootstrap#2699] opened 2017-09-19 19:52 UTC
https://github.com/valor-software/ngx-bootstrap/blob/b7a4c4db0a407f22172bd47d645eabc18a27b408/src/datepicker/bs-datepicker-input.directive.ts#L55-L65

datepicker directive not create new date with correct bsConfig.dateInputFormat or locale setted

i.e: 19/09/2017 (DD/MM/YYYY - spanish format) get invalid date
      09/11/2017 transform to 11/09/2017

**Comment by leomayer** [comment] 2017-09-20 06:46
I guess there are several issues with the locales - reported in different issues, e.g. #2622 as well as directly related to yours #2694 (which might be a the same as yours)

**Comment by valorkin** [comment] 2017-10-02 14:16
yes, duplicate of #2622 and #2694 
fixed with #2330

**Closed as completed by valorkin** 2017-10-02 14:16 UTC

**Comment by rjwijnen** [comment] 2017-10-02 14:36
How is this fixed with #2330 ?
