### ISSUE TITLE
Tabs with *ngIf are pushed to the end

### ISSUE THREAD

**Issue by jjmurre** [valor-software/ngx-bootstrap#1719] opened 2017-03-07 07:25 UTC
When I use an `*ngIf` condition to show/hide a tab, this tab  is pushed back to the last position.

So:
```
<tabset>
  <tab heading="One">Static content One</tab>
  <tab *ngIf="true" heading="Two">Static content Two</tab>
  <tab heading="Three">Static content Three</tab>
  <tab heading="Four">Static content Four</tab>
</tabset>

```
Tab "Two" is shown as the last tab.

**Comment by IlyaSurmay** [comment] 2017-11-09 10:36
Closing as a duplicate of #823

**Closed as completed by IlyaSurmay** 2017-11-09 10:36 UTC
Labels: comp(tabs)
