### ISSUE TITLE
bug(accordion): heading with markup not working

### ISSUE THREAD

**Issue by sylc** [valor-software/ngx-bootstrap#593] opened 2016-06-08 13:27 UTC
Hi, the accordion heading with markup is not working

from doc example:
`<i class="pull-right glyphicon" [ngClass]="{'glyphicon-chevron-down': group?.isOpen, 'glyphicon-chevron-right': !group?.isOpen}"></i>`

chevron never goes down when group is open.

thanks

**Comment by valorkin** [comment] 2016-06-08 14:45
It is still using DynamicContentLoader, and it loses context
It is known issue

**Comment by youngpayters** [comment] 2016-08-09 08:47
Not sure if this is a workaround or not but changing variable from `let group` to `#group` resolved it for me.

**Comment by calvinKG** [comment] 2016-08-28 16:12
@youngpayters  thanks it did solve the problem on my side. 

With the # it those reference the group on the html page.

**Comment by artemvfrolov** [comment] 2017-06-01 08:42
can't reproduce this issue, please provide more information

**Comment by IlyaSurmay** [comment] 2017-11-10 13:42
Closed as can't reproduce, will be reopened if we have sample to reproduce.
Header with markup works fine in demo  https://valor-software.com/ngx-bootstrap/#/accordion#simple-accordion

**Closed as completed by IlyaSurmay** 2017-11-10 13:42 UTC
Labels: issue, comp(accordion)
