### ISSUE TITLE
Control Modal from Service

### ISSUE THREAD

**Issue by dbogdantech101** [valor-software/ngx-bootstrap#1569] opened 2017-01-27 22:10 UTC
Not sure if this has been covered, but I'm hoping you can help:

I'm trying to control a Modal from a service. I know you have docs for controlling it from a it's parent component, but what if you wanted a larger service controlling it?

Ie.
A notification service

	<my-header></my-header>
	<my-notification></my-notification>
	<router-outlet></router-outlet>
	<my-footer></my-footer>

where every other component could use a service to control the my-notification component?

I haven't been able to find a way to access the modal inside my-notification from another component, any thoughts?

**Comment by GuskiS** [comment] 2017-01-29 21:52
You should look into `@ngrx/store`. Idea is that you have a global holding place for what ever you want. In this example, when ever you need to show your modal window you tell the store, update it, and make sure modal window is listening (`subscribed`) to these changes. Hope this helps.

**Comment by valorkin** [comment] 2017-01-31 10:49
+1 to @GuskiS 
and ModalService is a planned feature, which could help you a lot

**Comment by valorkin** [comment] 2017-01-31 10:50
closing as a duplicate of https://github.com/valor-software/ng2-bootstrap/issues/579
will be starting to implementing this one

**Closed as completed by valorkin** 2017-01-31 10:50 UTC
