### ISSUE TITLE
Do you have any value to confirm before delete tab from template ?

### ISSUE THREAD

**Issue by rainstormza** [valor-software/ngx-bootstrap#1585] opened 2017-02-01 08:19 UTC
Do you have any value to confirm before delete tab from template ?

I need ability to confirm or cancel tab that I want to delete

thanks

**Comment by valorkin** [comment] 2017-02-15 23:21
cancelable events is a planned feature

**Comment by IlyaSurmay** [comment] 2017-11-09 11:29
Closing as a duplicate of #786

**Closed as completed by IlyaSurmay** 2017-11-09 11:29 UTC
Labels: enhancement, comp(tabs)
