### ISSUE TITLE
angular-cli + ng2-bootstrap build error

### ISSUE THREAD

**Issue by adam-tychoniewicz** [valor-software/ngx-bootstrap#347] opened 2016-03-30 12:25 UTC
Project setup with https://github.com/angular/angular-cli
package.json contains: "ng2-bootstrap": "^1.0.7"

When tryiyng to import any directive im my app.ts file, and while running ng-build, error occured
![screenshot from 2016-03-30 10-51-23](https://cloud.githubusercontent.com/assets/7754206/14141996/22337da8-f683-11e5-8b87-7ef3d56dbfaa.png)

**Comment by adam-tychoniewicz** [comment] 2016-03-31 13:11
If it could help, in broccoli-typescript.js you can try/catch on fs.linkSync (_outputFile method).
This fix build issue, but why we need that only in ng2-bootstrap library with angular-cli?

**Comment by valorkin** [comment] 2016-03-31 20:19
not sure where the issue is
but please try with the latest version

**Comment by adam-tychoniewicz** [comment] 2016-04-01 11:35
Now problem is gone :)
Thank you very much :)

**Comment by valorkin** [comment] 2016-04-01 11:44
awesome! closing :)

**Closed as completed by valorkin** 2016-04-01 11:44 UTC
