### ISSUE TITLE
Typeahead: How to set initial data model value?

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#4253] opened 2018-04-20 14:04 UTC
It's not clear to me how to set an initial data model value for the typeahead component? I only see the output event 'typeaheadOnSelect' after user selection from the dropdown. But since I use the component within an edit form, it's essential to initialize the component with an equivalent object coming from the DB. How to do that??

I'm not talking about the ngModel value shown to the user. I already read that it's only possible to use a string instead of an object.

**Comment by marcelorl** [comment] 2018-04-24 18:16
It looks like there is already an issue opened for it and no way to set initial data for typeahead component.

@twosandy has suggested a temporary solution for this:
https://github.com/valor-software/ngx-bootstrap/issues/749#issuecomment-378032815

**Comment by Domainv** [comment] 2018-09-20 09:44
Closed as duplicate of #749

**Closed as completed by Domainv** 2018-09-20 09:44 UTC
Labels: question, comp(typeahead)
