### ISSUE TITLE
Typeahead: Erro while return after select item.

### ISSUE THREAD

**Issue by jcebidanes** [valor-software/ngx-bootstrap#3158] opened 2017-12-01 16:30 UTC
A have a formbuilder with field **_conselho_** to store **id** attribute .
I use  **typeaheadItemTemplate** to show **desc** attribute and **typeaheadOptionField** to get value attribute **id** to field **_conselho_**. This almost work. While select item the value go to field **_conselho_** correctly, but in the component show the value de **_conselho_** field instead the value the **desc** attribute. 

Steps:
Initial list allConselho correctly. Show only de desc.

I select the item "Conselho B". In formbuilder value 2 bind correctly.

But now in the component show de value 2 instead the keep "Conselho B".

### Bug description or feature request:

**AppComponent.ts**
```

allConselho= [
  {id: 1, desc: 'Conselho A'},
  {id: 2, desc: 'Conselho B'},
  {id: 3, desc: 'Conselho C'},
  {id: 4, desc: 'Conselho D'},
];

this.formTest = this.formBuilder.group({
        conselho: [null]
});
```

**AppComponent.html**
```
<form class="form-horizontal" [formGroup]="formTest">

<ng-template #customItemTemplate let-model="item" let-index="index">
      {{model.desc}}
</ng-template>
<input formControlName="conselho"
   [typeahead]="allConcelho"
   [typeaheadItemTemplate]="customItemTemplate"
   typeaheadOptionField="id"
   >
</form>            
```

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.9
Angular: 5.0.3
Build system: Angular CLI 1.5.2

**Comment by IlyaSurmay** [comment] 2017-12-04 11:47
Hi! `typeaheadOptionField` option defines which field will be used to set `ngModel`, so the same value will be displayed in typeahead input field.

Looks like a duplicate of #2335 so closing it.

**Closed as completed by IlyaSurmay** 2017-12-04 11:47 UTC
Labels: comp(typeahead)

**Comment by jcebidanes** [comment] 2017-12-04 15:52
Not exist who show "name" and save "id" ?
