### ISSUE TITLE
Please remove unreachable code (TS error)

### ISSUE THREAD

**Issue by born2net** [valor-software/ngx-bootstrap#178] opened 2016-02-12 17:16 UTC
in ng2-bootstrap/components/timepicker/timepicker.component.ts

remove

```
// Evaluate from template
    let hours = this.getHoursFromTemplate();
    let minutes = this.getMinutesFromTemplate();
    if (isDefined(hours) && isDefined(minutes)) {
      this.selected.setHours(hours);
      this.refresh();
    }
```

as TS complains of non reachable code

tx

Sean

**Comment by valorkin** [comment] 2016-02-15 07:39
please use ts 1.7.5 until 1.8 is supported by ng2
duplicate of #116

**Closed as completed by valorkin** 2016-02-15 07:39 UTC

**Comment by born2net** [comment] 2016-02-15 15:34
ok tx
