### ISSUE TITLE
chore(build): make npm script windows compatible

### ISSUE THREAD

**Issue by ishara** [valor-software/ngx-bootstrap#493] opened 2016-05-10 13:07 UTC
I just checkout ng2-bootstrap try to build ng2-bootstarp itself and could not run npm install.

Can u update contributor development guide to start and test?

D:\RNDA\AngulerJS\ishara\ng2-bootstrap>npm install

> node-zopfli@1.4.0 install D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v47-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@5.10.1 (node-v47 ABI) (falling back to source compile with node-gyp)

D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Users\ishara\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Users\ishara\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64\zopfli.node --module_name=zopfli --module_path=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64 )  else (node "" configure --fallback-to-build --module=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64\zopfli.node --module_name=zopfli --module_path=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64 )

D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Users\ishara\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64\zopfli.node --module_name=zopfli --module_path=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64 )  else (node "" build --fallback-to-build --module=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64\zopfli.node --module_name=zopfli --module_path=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64 )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the compon
ent to the system path if it is installed elsewhere.  [D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ishara\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\ishara\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "build" "--fallback-to-build" "--module=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64\zopfli.node" "--module_name=zopfli" "--module_path=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64"
gyp ERR! cwd D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64\zopfli.node --module_name=zopfli --module_path=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli
node-pre-gyp ERR! node -v v5.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64\zopfli.node --module_name=zopfli --module_path=D:\RNDA\AngulerJS\ishara\ng2-bootstrap\node_modules\node-zopfli\lib\binding\node-v47-win32-x64' (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1

> ng2-bootstrap@1.0.16 prepublish D:\RNDA\AngulerJS\ishara\ng2-bootstrap
> npm run flow.clean && npm run flow.compile
> 
> ng2-bootstrap@1.0.16 flow.clean D:\RNDA\AngulerJS\ishara\ng2-bootstrap
> del bundles coverage demo-build typings "components/*_/_.+(js|d.ts|js.map)" dist "ng2-bootstrap.+(js|d.ts|js.map)"

Could Not Find D:\RNDA\AngulerJS\ishara\ng2-bootstrap\bundles
D:\RNDA\AngulerJS\ishara\ng2-bootstrap\demo-build*, Are you sure (Y/N)? y
Could Not Find D:\RNDA\AngulerJS\ishara\ng2-bootstrap\typings
The filename, directory name, or volume label syntax is incorrect.

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\ishara\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "flow.clean"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! ng2-bootstrap@1.0.16 flow.clean: `del bundles coverage demo-build typings "components/**/*.+(js|d.ts|js.map)" dist "ng2-bootstrap.+(js|d.ts|js.map)"`
npm ERR! Exit status 123
npm ERR!
npm ERR! Failed at the ng2-bootstrap@1.0.16 flow.clean script 'del bundles coverage demo-build typings "components/**/*.+(js|d.ts|js.map)" dist "ng2-bootstrap.+(js|d.ts|js.map)"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-bootstrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     del bundles coverage demo-build typings "components/**/*.+(js|d.ts|js.map)" dist "ng2-bootstrap.+(js|d.ts|js.map)"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-bootstrap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-bootstrap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\RNDA\AngulerJS\ishara\ng2-bootstrap\npm-debug.log

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\ishara\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! ng2-bootstrap@1.0.16 prepublish: `npm run flow.clean && npm run flow.compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-bootstrap@1.0.16 prepublish script 'npm run flow.clean && npm run flow.compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-bootstrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run flow.clean && npm run flow.compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-bootstrap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-bootstrap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\RNDA\AngulerJS\ishara\ng2-bootstrap\npm-debug.log

**Comment by valorkin** [comment] 2016-05-10 13:10
My npm scripts doesn't work on windows >.<

**Comment by weddell** [comment] 2016-05-19 23:28
@valorkin - Are you planning on getting the npm scripts to work on windows? It's a bit of a bummer.

**Comment by valorkin** [comment] 2016-05-20 10:44
I will appreciate any help with it
not top prio as for now

**Comment by ernitingoel** [comment] 2016-05-21 01:46
I am also facing the same problem

**Comment by not-for-me** [comment] 2016-05-23 01:13
+1

The "node-zopfl" package depends on "compression-webpack-plugin".
I temporally removed "compression-webpack-plugin" in my case.

**Comment by adrianfaciu** [comment] 2016-06-28 10:47
Played with this a bit, but in the end just did what @not-for-me suggested and removed "compression-webpack-plugin". Everything works fine after that.

**Edit** Another good workaround is to use the new Linux Bash Shell on windows feature. Just gave this a try and it works nice.

**Comment by Confusedfish** [comment] 2016-09-09 09:47
I managed to get things compiling locally on my Windows box. There were quite a few issues getting npm-gyp to compile but that sounds like a fairly common problem under windows. Python version etc and are nothing to do with ng2-bootstrap, refer to [https://github.com/nodejs/node-gyp](https://github.com/nodejs/node-gyp) & the handy list of problems at [https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules)

The changes specific to ng2-bootstrap were related to resolving the correct paths to things in project.json & bundle-system.js. There is a strong chance that this will break things under a linux environment, anyone able to test it still works?

**Comment by valorkin** [comment] 2016-09-09 10:07
I am working on Linux and mac, if can do a PR I can check it

**Comment by Confusedfish** [comment] 2016-09-09 10:10
Thanks @Valorkin it's the now misnamed [PR 942](https://github.com/valor-software/ng2-bootstrap/pull/942) which has another change to do with the ProgressBar in it. (I am new to Pull Requests, hence getting multiple changes into the one PR)

**Comment by Igonato** [comment] 2016-09-11 16:06
@Confusedfish looks good overall, only flow.clean still fails (try npm install on a fresh clone of your fork). The issue is mentioned in [del-cli](https://github.com/sindresorhus/del-cli) readme, you need to use `del-cli` because `del` clashes with a built-in Windows command.

I made a separate PR for this  (#953)

Seem to work alright, few errors during the `npm install` can be ignored, everything works at the end.

**Comment by valorkin** [comment] 2016-09-12 15:03
should be fixed with #953

**Closed as completed by valorkin** 2016-09-12 15:03 UTC
Labels: help wanted, effort1: easy (hours)

**Comment by Confusedfish** [comment] 2016-09-12 15:05
Cheers for picking up my mistake @Igonato
