### ISSUE TITLE
Month position is changed when the first date is selected 

### ISSUE THREAD

**Issue by biosis21** [valor-software/ngx-bootstrap#3594] opened 2018-01-30 20:59 UTC
Hi!
The main problem is when you show two months (displayMonths: 2) and select date in the second month, this month will change position from 2 to 1. My suggestion is to disable functionality automatically change month position.

**Comment by yigitbacakoglu** [comment] 2019-01-31 08:06
Any update on this? The behaviour is really annoying.

**Comment by Domainv** [comment] 2019-10-01 09:40
Duplicate of #5154

**Closed as completed by Domainv** 2019-10-01 09:40 UTC
Labels: enhancement, comp(datepicker)
