### ISSUE TITLE
ISO dates loaded to the reactive forms are showing invalid date

### ISSUE THREAD

**Issue by tbadlov** [valor-software/ngx-bootstrap#4020] opened 2018-03-16 22:12 UTC
### Bug description or feature request:
when an ISO date format is loaded to a reactive model it shows an invalid date.

### Plunker/StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-dpshux

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.3

Angular: 5.2.8

Bootstrap: 4.0

### Build system: Angular CLI, System.js, webpack, starter seed:

Angular CLI 1.7.3

**Comment by IlyaSurmay** [comment] 2018-03-19 09:59
closed as a duplicate of #3124

**Comment by IlyaSurmay** [comment] 2018-03-19 10:03
Datepicker model format is a `Date` object and you provided a string. This string has to be converted into a `Date` object before using it in datepicker.

**Closed as completed by IlyaSurmay** 2018-03-19 10:03 UTC
Labels: comp(datepicker)

**Comment by tbadlov** [comment] 2018-03-22 19:51
It used to work with version 2.0.beta8

**Comment by coffeymatt** [comment] 2018-05-14 11:53
@IlyaSurmay I think this should be reopened, datepicker should work with iso strings. Otherwise I have to process every date in the output from an api.

**Comment by grantbowering** [comment] 2018-05-16 16:17
agreed with the above; this means we can't just materialize from json and bind with ngModel, we have to transform it.  And it means that in typescript, if I expect it to be materialized as a `string`, but datepicker needs it as a `Date`, then I have to set that field in the dto's interface to type `any` so that I can assign a Date to it programmatically on load, and that's just weird.  
Is this really the intent/policy of this project?  I notice that `writeValue(value: Date | string)`...

**Comment by tbadlov** [comment] 2018-05-21 00:52
What's the rational behind making the property strict to `Date` type? No service will provide you a date property in the type `Date` so it is literally causing us to write unnecessary code to instantiate a date object with the property of the ISO date string. It should just allow to accept both `(Date | string)`

**Comment by akvaliya** [comment] 2019-04-04 10:50
This should reopened. This is really weird behavior.  I am using reactive forms & facing the exact same issue. Any updates on this issue?
