### ISSUE TITLE
Using *ngif on a tab causes odd behavior

### ISSUE THREAD

**Issue by Dan203** [valor-software/ngx-bootstrap#2586] opened 2017-09-06 21:42 UTC
http://plnkr.co/edit/eWpx1SIDx8iogeXUeHhw?p=preview

I want to be able to show/hide a tab dynamically while keeping it's position in the list.

**Comment by valorkin** [comment] 2017-09-07 20:12
ngIf removes component, completely
not always gracefully
better to do display:none
and you will not have to waste additional time on reinit of tab later

**Comment by Dan203** [comment] 2017-09-07 23:12
How do you use display:none to hide a tab? When I tried to use the angular [hidden] attribute it only hid the contents of the tab not the tab itself. 

http://plnkr.co/edit/jUlUKpqgqMaxpT5B4bvg?p=preview

**Comment by IlyaSurmay** [comment] 2017-10-04 13:19
Closing as a duplicate of #1719

**Closed as completed by IlyaSurmay** 2017-10-04 13:19 UTC
Labels: comp(tabs)
