### ISSUE TITLE
Hold modal logic in a separate component

### ISSUE THREAD

**Issue by smnbbrv** [valor-software/ngx-bootstrap#892] opened 2016-08-24 20:17 UTC
Hi guys,

I'm extensively using the library and I love it! Great tool to build the things fast.

However I really miss the way to modularize the modal dialogs (if I follow the steps described [here](https://valor-software.com/ng2-bootstrap/#/modals)). The current approach is working, but I don't find it too good to use it everywhere in the app because of the following reasons:
- There is no possibility to have a modal over modal. Yes, this might be not the best UX, but sometimes it really saves the day to have a modal which is called from another modal
- The modal is created inside of the component, so any `overflow: hidden` on the parent nodes breaks the layout
- There is no possibility to control the dialog flow from the controller side. I can use the `@ViewChild` decorator to get the directive and use it, but this is not the obvious way...
- It is quite not obvious how to reset the modal content. Once the modal content is rendered it is not changed. E.g. I have a form in a dialog, when I fill it and hide the dialog the data is still there => if I open the dialog again the form will have the same value. I solved it with `onHide` / `onShow` setting up a boolean flag in combination with `*ngIf` on `modal-body` element, but again it is not that clean solution
- Finally the HTML template becomes unbelievably big. Just an example: I have a page with 3 different dialogs and each of them takes more space than the original component.

I would really like to have some kind of modal control from the `Component` side, e.g. 

``` typescript
// keep the modal logic and template outside of the consumer component
import { MyModalComponent } from './blabla.component';

@Component(...)
export class MyModalConsumerComponent implements OnInit {

  // modal holder which is created once per consumer component
  private _modal: Modal;

  private _modal_another: Modal;

  public ngOnInit() {
    // create the modal which content is dynamically resolved from MyModalComponent
    this._modal = modalFactory.create(MyModalComponent, ...);
  }

  public ngOnDestroy() {
    this._modal.destroy();
  }

  public buttonclick() {
    this._modal.show();
  }

}
```

I already have an 80% working solution for all the cases above which reuses the components / services you already have, just extends them. If you find that useful I can prepare a pull request

**Comment by valorkin** [comment] 2016-09-02 14:23
@smnbbrv SUUURE! I would love to see a PR :)
Join slack and we can chat about it, and how we can merge it :)

**Comment by k-schneider** [comment] 2016-09-17 23:46
Any progress on this? Being able to create a modal from within a component would be hugely helpful in many scenarios.  Thanks!

**Comment by bhaskerchari** [comment] 2016-10-11 18:26
Hello @smnbbrv / @valorkin ,

Any progress or update on this as this would greatly help to deal with modal windows in a more cleaner and generic way.

Is it some thing still on your todo list or any WIP, please let us know.

Thanks in advance.

**Comment by valorkin** [comment] 2016-10-11 18:47
It's part of modal as a service feature

**Comment by smnbbrv** [comment] 2016-10-12 08:00
@bhaskerchari I think I won't have time to do that...

@valorkin is this feature under construction?

**Comment by valorkin** [comment] 2016-10-12 08:01
Yep, polishing AoT right now

**Comment by valorkin** [comment] 2017-01-31 10:50
closing as a duplicate of https://github.com/valor-software/ng2-bootstrap/issues/579
will be starting to implementing this one

**Closed as completed by valorkin** 2017-01-31 10:50 UTC
Labels: enhancement, comp(modal)
